# Generated by Django 5.2.15 on 2026-06-11 20:42

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Project categories',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDetailPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_hero_eyebrow', models.CharField(default='Project Case Study', max_length=120)),
                ('show_summary', models.BooleanField(default=True)),
                ('show_quick_facts', models.BooleanField(default=True)),
                ('show_gallery', models.BooleanField(default=True)),
                ('show_case_study_blocks', models.BooleanField(default=True)),
                ('show_metrics', models.BooleanField(default=True)),
                ('show_documents', models.BooleanField(default=True)),
                ('show_related_projects', models.BooleanField(default=True)),
                ('show_cta', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project Detail Page Settings',
                'verbose_name_plural': 'Project Detail Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ProjectListPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Projects Overview', max_length=120)),
                ('hero_title', models.CharField(default='Projects Delivered with Quality, Safety and Reliability.', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='Explore successfully delivered projects spanning telecommunications, civil, electrical and architectural solutions.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='projects/list-page/')),
                ('intro_title', models.CharField(default='Proof through delivered work.', max_length=255)),
                ('intro_text', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('show_stats', models.BooleanField(default=True)),
                ('show_category_tabs', models.BooleanField(default=True)),
                ('show_search', models.BooleanField(default=True)),
                ('show_featured_project', models.BooleanField(default=True)),
                ('show_client_strip', models.BooleanField(default=True)),
                ('show_cta', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project List Page Settings',
                'verbose_name_plural': 'Project List Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ProjectListStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('contractor_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('planned', 'Planned')], default='completed', max_length=30)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('short_description', models.TextField(blank=True)),
                ('summary', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('challenge', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('scope', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('solution', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('outcomes', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('project_profile', models.FileField(blank=True, null=True, upload_to='projects/documents/')),
                ('is_featured', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('services', models.ManyToManyField(blank=True, related_name='projects', to='services.service')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Interested in a similar project?', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Talk to our team about your project requirements.')),
                ('button_text', models.CharField(default='Start a Project', max_length=80)),
                ('button_url', models.CharField(default='/contact/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='projects/files/')),
                ('description', models.TextField(blank=True)),
                ('file_type', models.CharField(blank=True, default='PDF', max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectScopeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_items', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
    ]
