# Generated by Django 5.2.15 on 2026-06-11 20:42

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceDetailPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_hero_eyebrow', models.CharField(default='Service Detail', max_length=120)),
                ('show_key_points', models.BooleanField(default=True)),
                ('show_deliverables', models.BooleanField(default=True)),
                ('show_features', models.BooleanField(default=True)),
                ('show_process', models.BooleanField(default=True)),
                ('show_related_projects', models.BooleanField(default=True)),
                ('show_brochure', models.BooleanField(default=True)),
                ('show_faqs', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Detail Page Settings',
                'verbose_name_plural': 'Service Detail Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceListFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceListPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(default='Integrated Engineering Solutions. Built on Expertise.', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='End-to-end engineering services that power safe, efficient and sustainable buildings and infrastructure.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/list-page/')),
                ('eyebrow', models.CharField(default='Services Overview', max_length=120)),
                ('intro_title', models.CharField(default='Services designed for reliable delivery.', max_length=255)),
                ('intro_text', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('show_search', models.BooleanField(default=True)),
                ('show_category_tabs', models.BooleanField(default=True)),
                ('show_featured_service', models.BooleanField(default=True)),
                ('show_process', models.BooleanField(default=True)),
                ('show_faqs', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service List Page Settings',
                'verbose_name_plural': 'Service List Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceListProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('icon_text', models.CharField(blank=True, default='⚙', max_length=40)),
                ('short_description', models.TextField(blank=True)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='services/brochures/')),
                ('is_featured', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Have a Project in Mind?', max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Get in Touch', max_length=80)),
                ('button_url', models.CharField(default='/contact/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='services.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='services.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceKeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_points', to='services.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='services.service')),
            ],
            options={
                'ordering': ['step_number', 'sort_order', 'id'],
                'abstract': False,
            },
        ),
    ]
