# Generated by Django 5.2.15 on 2026-06-11 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Contact Us', max_length=120)),
                ('hero_title', models.CharField(default='Contact Us. We’re Here to Help.', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='Have a question, need a quote or ready to start your next project? Our team is ready to listen.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='contact/page/')),
                ('intro_title', models.CharField(default='Let’s Build Something Great Together', max_length=255)),
                ('intro_text', models.TextField(blank=True, default='Reach out to us for project inquiries, collaborations or support. We’ll get back to you promptly.')),
                ('show_contact_methods', models.BooleanField(default=True)),
                ('show_offices', models.BooleanField(default=True)),
                ('show_business_hours', models.BooleanField(default=True)),
                ('show_map', models.BooleanField(default=True)),
                ('show_faqs', models.BooleanField(default=True)),
                ('show_whatsapp_cta', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Page Settings',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
        migrations.CreateModel(
            name='InquirySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('email_to', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject_text', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('consent', models.BooleanField(default=False)),
                ('source_page', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('responded', 'Responded'), ('resolved', 'Resolved'), ('spam', 'Spam'), ('archived', 'Archived')], default='new', max_length=30)),
                ('admin_note', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_spam_suspected', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.inquirysubject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
