import zlib

from django import template
from django.utils.safestring import mark_safe
from django.utils.translation import get_language
from apps.core.models import LocalizedContent

register = template.Library()


def _is_bad_demo_translation(value):
    text = str(value or "").strip()
    bad_prefixes = ("ترجمة:", "Translation:", "翻译:")
    return any(text.startswith(prefix) for prefix in bad_prefixes)


def _lookup(obj, field_name):
    if obj is None:
        return ""
    lang = get_language() or "en"
    content_type = obj.__class__.__name__.lower()
    object_id = getattr(obj, "id", None)
    fallback = getattr(obj, field_name, "")
    if not object_id or lang == "en":
        return fallback
    override = LocalizedContent.objects.filter(
        content_type=content_type,
        object_id=object_id,
        language_code=lang,
        field_name=field_name,
    ).first()
    fallback_map = globals().get("VISIBLE_CMS_FALLBACK_TRANSLATIONS", {}).get(lang, {})
    if override and override.text and not _is_bad_demo_translation(override.text):
        override_text = str(override.text).strip()
        # If an older seed stored an exact English copy as the localized value,
        # prefer the visible runtime translation instead of showing English on /ar/ or /zh-hans/.
        if fallback in fallback_map and override_text == str(fallback).strip():
            return fallback_map[fallback]
        return override.text
    if fallback in fallback_map:
        return fallback_map[fallback]
    # Many rich-text CMS fields store the English source wrapped in simple HTML
    # such as <p>...</p>. Match the visible text so Arabic/Chinese fallbacks
    # still display instead of English paragraphs.
    try:
        from django.utils.html import strip_tags
        raw_fallback = str(fallback or "")
        plain_fallback = " ".join(strip_tags(raw_fallback).split())
        if plain_fallback in fallback_map:
            translated = fallback_map[plain_fallback]
            if raw_fallback.strip().startswith("<"):
                return f"<p>{translated}</p>"
            return translated
    except Exception:
        pass
    return fallback


@register.simple_tag
def localized(obj, field_name):
    return mark_safe(_lookup(obj, field_name))


@register.simple_tag
def localized_plain(obj, field_name):
    value = _lookup(obj, field_name)
    return str(value)


@register.simple_tag
def localized_meta(obj, field_name, fallback=""):
    value = _lookup(obj, field_name)
    return str(value or fallback or "")




@register.simple_tag
def localized_lines(obj, field_name):
    """Return localized multi-line field as a clean list for templates."""
    value = _lookup(obj, field_name)
    return [line.strip() for line in str(value or "").splitlines() if line.strip()]

@register.simple_tag(takes_context=True)
def localized_url(context, url):
    """Keep internal links inside the current language prefix."""
    if not url:
        return "#"

    value = str(url)

    # External, mail, tel, anchors should not be changed.
    if value.startswith(("http://", "https://", "mailto:", "tel:", "#")):
        return value

    request = context.get("request")
    lang = get_language() or "en"

    if not value.startswith("/"):
        value = "/" + value

    # Remove existing language prefix first, then add current language if needed.
    for prefix in ["/ar", "/zh-hans", "/en"]:
        if value == prefix:
            value = "/"
            break
        if value.startswith(prefix + "/"):
            value = value[len(prefix):] or "/"
            break

    if lang == "ar":
        return "/ar" + value if value != "/" else "/ar/"
    if lang == "zh-hans":
        return "/zh-hans" + value if value != "/" else "/zh-hans/"
    return value


STATIC_TRANSLATIONS = {
    "ar": {
        "Home": "الرئيسية",
        "About Us": "من نحن",
        "Services": "الخدمات",
        "Projects": "المشاريع",
        "Clients": "العملاء",
        "Certificates": "الشهادات",
        "Downloads": "التحميلات",
        "Careers": "الوظائف",
        "Open Jobs": "الوظائف المتاحة",
        "Apply Online": "التقديم عبر الإنترنت",
        "Contact HR": "تواصل مع الموارد البشرية",
        "View Open Jobs": "عرض الوظائف المتاحة",
        "Open roles": "وظائف متاحة",
        "All Departments": "كل الأقسام",
        "All Job Types": "كل أنواع الوظائف",
        "Featured First": "المميزة أولاً",
        "Deadline": "آخر موعد",
        "View Details": "عرض التفاصيل",
        "Apply for this Job": "التقديم لهذه الوظيفة",
        "Apply Now": "قدم الآن",
        "Job Overview": "نظرة عامة على الوظيفة",
        "Job Code": "رمز الوظيفة",
        "Department": "القسم",
        "Level": "المستوى",
        "Salary": "الراتب",
        "About the Role": "عن الوظيفة",
        "Qualifications": "المؤهلات",
        "Preferred Skills": "المهارات المفضلة",
        "Read Details": "قراءة التفاصيل",
        "Open until filled": "مفتوحة حتى اكتمال التوظيف",
        "Ready to apply?": "جاهز للتقديم؟",
        "More Open Roles": "وظائف أخرى متاحة",
        "Related opportunities": "فرص ذات صلة",
        "Responsibilities": "المسؤوليات",
        "Requirements": "المتطلبات",
        "Submit Application": "إرسال الطلب",
        "Application Submitted": "تم إرسال الطلب",
        "Contact": "اتصل بنا",
        "Contact Us": "اتصل بنا",
        "Get in Touch": "تواصل معنا",
        "Send Us an Inquiry": "أرسل استفسارك",
        "Fill out the form below and our team will get back to you.": "املأ النموذج أدناه وسيقوم فريقنا بالتواصل معك.",
        "Send Inquiry": "إرسال الاستفسار",
        "I agree to be contacted by": "أوافق على أن يتم التواصل معي من قبل",
        "Our Office": "مكتبنا",
        "Frequently Asked Questions": "الأسئلة الشائعة",
        "Need Immediate Support?": "هل تحتاج إلى دعم فوري؟",
        "Use the configured WhatsApp contact method for fast communication.": "استخدم وسيلة التواصل عبر واتساب للتواصل السريع.",
        "Chat on WhatsApp": "تواصل عبر واتساب",
        "Business Hours": "ساعات العمل",
        "Get Directions": "احصل على الاتجاهات",
        "Office Location": "موقع المكتب",
        "Call Us": "اتصل بنا",
        "WhatsApp": "واتساب",
        "Email Us": "راسلنا عبر البريد",
        "Request a Document": "طلب مستند",
        "Submit Request": "إرسال الطلب",
        "Tell us which document you need and our team will respond soon.": "أخبرنا بالمستند الذي تحتاجه وسيقوم فريقنا بالرد عليك قريباً.",
        "Document Center": "مركز المستندات",
        "All Documents": "كل المستندات",
        "Document Name": "اسم المستند",
        "Category": "الفئة",
        "Type": "النوع",
        "Size": "الحجم",
        "Version": "الإصدار",
        "Access": "الوصول",
        "Actions": "الإجراءات",
        "Preview": "معاينة",
        "Download": "تحميل",
        "Request": "طلب",
        "All Services": "كل الخدمات",
        "All Projects": "كل المشاريع",
        "All Clients": "كل العملاء",
        "Filter": "تصفية",
        "Filter Projects": "تصفية المشاريع",
        "All Statuses": "كل الحالات",
        "All Years": "كل السنوات",
        "All File Types": "كل أنواع الملفات",
        "Newest": "الأحدث",
        "Name": "الاسم",
        "Most Downloaded": "الأكثر تحميلاً",
        "Project Summary": "ملخص المشروع",
        "Project Gallery": "معرض المشروع",
        "Project Metrics": "مؤشرات المشروع",
        "Project Documents": "مستندات المشروع",
        "Project at a Glance": "لمحة عن المشروع",
        "Related Projects": "مشاريع ذات صلة",
        "Related Services": "خدمات ذات صلة",
        "Client": "العميل",
        "Contractor": "المقاول",
        "Location": "الموقع",
        "Status": "الحالة",
        "Duration": "المدة",
        "Year": "السنة",
        "Start a Project": "ابدأ مشروعك",
        "Download Project Profile": "تحميل ملف المشروع",
        "Accreditations": "الاعتمادات",
        "Compliance Focus": "التركيز على الامتثال",
        "Company Documents": "مستندات الشركة",
        "Download supporting documents.": "قم بتحميل المستندات الداعمة.",
        "No services found.": "لم يتم العثور على خدمات.",
        "No projects found.": "لم يتم العثور على مشاريع.",
        "No documents found.": "لم يتم العثور على مستندات.",
        "No clients yet.": "لا يوجد عملاء بعد.",
        "No partners yet.": "لا يوجد شركاء بعد.",
        "No certificates yet.": "لا توجد شهادات بعد.",
        "No standards yet.": "لا توجد معايير بعد.",
        "No accreditations yet.": "لا توجد اعتمادات بعد.",
        "How quickly will I receive a response?": "ما مدى سرعة الرد على استفساري؟",
        "Do you offer services outside Dammam?": "هل تقدمون خدمات خارج الدمام؟",
        "Let’s Build Something Great Together": "لنبنِ شيئاً عظيماً معاً",
        "Reach out to us for project inquiries, collaborations or support. We’ll get back to you promptly.": "تواصل معنا للاستفسارات أو التعاون أو الدعم، وسنعود إليك في أقرب وقت.",
        "Page Not Found": "الصفحة غير موجودة",
        "Back to Home": "العودة إلى الرئيسية",
        "Something Went Wrong": "حدث خطأ ما",
        "Open": "فتح",
        "Dashboard": "لوحة التحكم",
        "Translation Center": "مركز الترجمة",
    },
    "zh-hans": {
        "Home": "首页",
        "About Us": "关于我们",
        "Services": "服务",
        "Projects": "项目",
        "Clients": "客户",
        "Certificates": "认证",
        "Downloads": "下载",
        "Careers": "招聘",
        "Open Jobs": "开放职位",
        "Apply Online": "在线申请",
        "Contact HR": "联系人力资源",
        "View Open Jobs": "查看开放职位",
        "Open roles": "开放职位",
        "All Departments": "所有部门",
        "All Job Types": "所有职位类型",
        "Featured First": "优先显示精选",
        "Deadline": "截止日期",
        "View Details": "查看详情",
        "Apply for this Job": "申请此职位",
        "Apply Now": "立即申请",
        "Job Overview": "职位概览",
        "Job Code": "职位编号",
        "Department": "部门",
        "Level": "级别",
        "Salary": "薪资",
        "About the Role": "职位介绍",
        "Qualifications": "资格要求",
        "Preferred Skills": "优先技能",
        "Read Details": "阅读详情",
        "Open until filled": "招满为止",
        "Ready to apply?": "准备申请？",
        "More Open Roles": "更多开放职位",
        "Related opportunities": "相关机会",
        "Responsibilities": "职责",
        "Requirements": "要求",
        "Submit Application": "提交申请",
        "Application Submitted": "申请已提交",
        "Contact": "联系",
        "Contact Us": "联系我们",
        "Get in Touch": "联系我们",
        "Send Us an Inquiry": "发送咨询",
        "Fill out the form below and our team will get back to you.": "请填写下面的表格，我们的团队会尽快与您联系。",
        "Send Inquiry": "发送咨询",
        "I agree to be contacted by": "我同意被联系，联系方为",
        "Our Office": "我们的办公室",
        "Frequently Asked Questions": "常见问题",
        "Need Immediate Support?": "需要即时支持？",
        "Use the configured WhatsApp contact method for fast communication.": "请使用已配置的 WhatsApp 联系方式进行快速沟通。",
        "Chat on WhatsApp": "通过 WhatsApp 聊天",
        "Business Hours": "营业时间",
        "Get Directions": "获取路线",
        "Office Location": "办公室位置",
        "Call Us": "致电我们",
        "WhatsApp": "WhatsApp",
        "Email Us": "邮件联系",
        "Request a Document": "申请文件",
        "Submit Request": "提交申请",
        "Tell us which document you need and our team will respond soon.": "请告诉我们您需要的文件，我们的团队会尽快回复。",
        "Document Center": "文件中心",
        "All Documents": "所有文件",
        "Document Name": "文件名称",
        "Category": "类别",
        "Type": "类型",
        "Size": "大小",
        "Version": "版本",
        "Access": "访问权限",
        "Actions": "操作",
        "Preview": "预览",
        "Download": "下载",
        "Request": "申请",
        "All Services": "所有服务",
        "All Projects": "所有项目",
        "All Clients": "所有客户",
        "Filter": "筛选",
        "Filter Projects": "筛选项目",
        "All Statuses": "所有状态",
        "All Years": "所有年份",
        "All File Types": "所有文件类型",
        "Newest": "最新",
        "Name": "名称",
        "Most Downloaded": "下载最多",
        "Project Summary": "项目摘要",
        "Project Gallery": "项目图库",
        "Project Metrics": "项目指标",
        "Project Documents": "项目文件",
        "Project at a Glance": "项目概览",
        "Related Projects": "相关项目",
        "Related Services": "相关服务",
        "Client": "客户",
        "Contractor": "承包商",
        "Location": "位置",
        "Status": "状态",
        "Duration": "周期",
        "Year": "年份",
        "Start a Project": "开始项目",
        "Download Project Profile": "下载项目资料",
        "Accreditations": "资质认可",
        "Compliance Focus": "合规重点",
        "Company Documents": "公司文件",
        "Download supporting documents.": "下载支持文件。",
        "No services found.": "未找到服务。",
        "No projects found.": "未找到项目。",
        "No documents found.": "未找到文件。",
        "No clients yet.": "暂无客户。",
        "No partners yet.": "暂无合作伙伴。",
        "No certificates yet.": "暂无证书。",
        "No standards yet.": "暂无标准。",
        "No accreditations yet.": "暂无资质认可。",
        "How quickly will I receive a response?": "我多久能收到回复？",
        "Do you offer services outside Dammam?": "你们在达曼以外提供服务吗？",
        "Let’s Build Something Great Together": "让我们一起创造卓越",
        "Reach out to us for project inquiries, collaborations or support. We’ll get back to you promptly.": "请联系我们进行项目咨询、合作或支持，我们会尽快回复。",
        "Page Not Found": "页面未找到",
        "Back to Home": "返回首页",
        "Something Went Wrong": "出现错误",
        "Open": "打开",
        "Dashboard": "仪表盘",
        "Translation Center": "翻译中心",
    },
}


# Upgrade 137: runtime fallback for visible CMS card text if a database row is added
# manually and localization rows have not been seeded yet.
VISIBLE_CMS_FALLBACK_TRANSLATIONS = {
    "ar": {
        "Safety-Focused Execution": "تنفيذ يركز على السلامة",
        "We prioritize safe work practices and reliable site execution.": "نلتزم بممارسات عمل آمنة وتنفيذ موقعي موثوق في كل مرحلة.",
        "Skilled Workforce": "كوادر فنية مؤهلة",
        "Qualified personnel capable of supporting complex requirements.": "فريق مؤهل قادر على دعم متطلبات المشاريع المعقدة بكفاءة.",
        "Flexible Contract Support": "دعم تعاقدي مرن",
        "Scalable project-team and equipment support according to project needs.": "دعم قابل للتوسع لفرق المشروع والمعدات وفق احتياجات كل مشروع.",
        "Quality Commitment": "التزام بالجودة",
        "Work guided by quality, efficiency and client satisfaction.": "عمل منظم يستند إلى الجودة والكفاءة ورضا العملاء.",
        "Why Choose SESCCO": "لماذا تختار SESCCO",
        "A dependable partner for quality, safety and execution.": "شريك موثوق للجودة والسلامة والتنفيذ.",

        "Trust & Respect": "الثقة والاحترام",
        "We keep our promises, communicate clearly and build relationships on accountability, professionalism and respect.": "نلتزم بوعودنا ونتواصل بوضوح ونبني العلاقات على المسؤولية والاحتراف والاحترام.",
        "Safe Workplace": "بيئة عمل آمنة",
        "We protect people, sites and the environment through safe work practices and responsible supervision.": "نحمي الأفراد والمواقع والبيئة من خلال ممارسات عمل آمنة وإشراف مسؤول.",
        "Quality Execution": "تنفيذ عالي الجودة",
        "We focus on reliable delivery, proper documentation and workmanship that meets project requirements.": "نركز على التسليم الموثوق والتوثيق السليم وجودة العمل التي تلبي متطلبات المشروع.",
        "Foundation": "التأسيس",
        "SESCCO was established to deliver dependable engineering and contracting services.": "تأسست SESCCO لتقديم خدمات هندسية ومقاولات موثوقة.",
        "Major Civil Works": "أعمال مدنية رئيسية",
        "Participation in industrial civil and infrastructure works.": "المشاركة في أعمال مدنية وصناعية وبنية تحتية.",
        "Pipeline Experience": "خبرة خطوط الأنابيب",
        "Execution support for ROW, trench excavation, backfilling and berming works.": "دعم تنفيذ أعمال مسارات خطوط الأنابيب والحفر والردم والتسوية.",
        "Expanded Project Portfolio": "توسع محفظة المشاريع",
        "Continued delivery across electrical, civil, fit-out and contract support projects.": "استمرار التنفيذ في المشاريع الكهربائية والمدنية والتشطيبات والدعم التعاقدي.",
    },
    "zh-hans": {
        "Safety-Focused Execution": "以安全为核心的执行",
        "We prioritize safe work practices and reliable site execution.": "我们重视安全作业实践，并确保现场执行可靠有序。",
        "Skilled Workforce": "熟练专业团队",
        "Qualified personnel capable of supporting complex requirements.": "合格人员能够高效支持复杂项目需求。",
        "Flexible Contract Support": "灵活合同支持",
        "Scalable project-team and equipment support according to project needs.": "根据项目需求提供可扩展的项目团队与设备支持。",
        "Quality Commitment": "质量承诺",
        "Work guided by quality, efficiency and client satisfaction.": "以质量、效率和客户满意度为导向开展工作。",
        "Why Choose SESCCO": "为什么选择 SESCCO",
        "A dependable partner for quality, safety and execution.": "质量、安全和执行力的可靠伙伴。",

        "Trust & Respect": "信任与尊重",
        "We keep our promises, communicate clearly and build relationships on accountability, professionalism and respect.": "我们信守承诺、清晰沟通，并以责任、专业和尊重建立合作关系。",
        "Safe Workplace": "安全工作环境",
        "We protect people, sites and the environment through safe work practices and responsible supervision.": "通过安全作业实践和负责任的监督，保护人员、现场和环境。",
        "Quality Execution": "高质量执行",
        "We focus on reliable delivery, proper documentation and workmanship that meets project requirements.": "我们专注于可靠交付、规范文件和满足项目要求的施工质量。",
        "Foundation": "成立",
        "SESCCO was established to deliver dependable engineering and contracting services.": "SESCCO 成立，专注提供可靠的工程与承包服务。",
        "Major Civil Works": "主要土建工程",
        "Participation in industrial civil and infrastructure works.": "参与工业土建和基础设施工程。",
        "Pipeline Experience": "管线项目经验",
        "Execution support for ROW, trench excavation, backfilling and berming works.": "支持管线走廊、沟槽开挖、回填和整平等施工。",
        "Expanded Project Portfolio": "项目组合扩展",
        "Continued delivery across electrical, civil, fit-out and contract support projects.": "持续交付电气、土建、装修和合同支持项目。",
    },
}


# Career public UI labels added in Career Upgrade 3.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "01": "01",
    "02": "02",
    "About": "عن الوظيفة",
    "Additional details": "تفاصيل إضافية",
    "All": "الكل",
    "Application role": "الوظيفة المقدمة لها",
    "Apply": "تقديم",
    "Apply before": "قدم قبل",
    "Apply for": "التقديم على",
    "Apply online": "التقديم عبر الإنترنت",
    "Attach certificates or licenses if they support the role.": "أرفق الشهادات أو التراخيص إذا كانت تدعم الوظيفة.",
    "Back to Careers": "العودة إلى الوظائف",
    "Back to Job": "العودة إلى الوظيفة",
    "Candidate details": "بيانات المتقدم",
    "Certificates / education": "الشهادات / التعليم",
    "Clear filters": "مسح التصفية",
    "Currently hiring": "التوظيف متاح حالياً",
    "Details": "التفاصيل",
    "Documents": "المستندات",
    "Experience": "الخبرة",
    "Featured": "مميزة",
    "General": "عام",
    "HR review": "مراجعة الموارد البشرية",
    "Interview": "المقابلة",
    "Interview invite": "دعوة مقابلة",
    "Invitation details will be sent by email.": "سيتم إرسال تفاصيل الدعوة عبر البريد الإلكتروني.",
    "Job Application": "طلب توظيف",
    "Job Opening": "فرصة وظيفية",
    "Job Type": "نوع الوظيفة",
    "Job overview": "نظرة عامة على الوظيفة",
    "Make sure your email and phone number are correct.": "تأكد من صحة البريد الإلكتروني ورقم الهاتف.",
    "Optional certificate/license · PDF/DOC/DOCX · max 8MB": "شهادة/رخصة اختيارية · PDF/DOC/DOCX · بحد أقصى 8MB",
    "Optional supporting document · PDF/DOC/DOCX · max 8MB": "مستند داعم اختياري · PDF/DOC/DOCX · بحد أقصى 8MB",
    "Optional multiple files · PDF/DOC/DOCX · max 8MB each": "ملفات اختيارية متعددة · PDF/DOC/DOCX · بحد أقصى 8MB لكل ملف",
    "Personal information": "المعلومات الشخصية",
    "Positions": "عدد الشواغر",
    "Preferred": "مفضل",
    "Required · PDF/DOC/DOCX · max 8MB": "مطلوب · PDF/DOC/DOCX · بحد أقصى 8MB",
    "Reset search": "إعادة ضبط البحث",
    "Role summary": "ملخص الوظيفة",
    "Search role, skill, job code, or location": "ابحث عن وظيفة أو مهارة أو رمز وظيفة أو موقع",
    "Selected applicants will be contacted.": "سيتم التواصل مع المتقدمين المختارين.",
    "Shortlist": "القائمة المختصرة",
    "Shortlisted applicants will receive interview details by email.": "سيتلقى المتقدمون المختارون تفاصيل المقابلة عبر البريد الإلكتروني.",
    "Showing": "عرض",
    "Skills": "المهارات",
    "Submit for HR review": "إرسال للمراجعة من الموارد البشرية",
    "This information helps HR contact and evaluate the applicant correctly.": "تساعد هذه المعلومات الموارد البشرية على التواصل مع المتقدم وتقييمه بشكل صحيح.",
    "Upload CV": "رفع السيرة الذاتية",
    "Upload a CV and any supporting documents that match the job requirements.": "ارفع السيرة الذاتية وأي مستندات داعمة مطابقة لمتطلبات الوظيفة.",
    "Use PDF, DOC or DOCX files only.": "استخدم ملفات PDF أو DOC أو DOCX فقط.",
    "What we need": "ما نحتاجه",
    "What you will do": "ما ستقوم به",
    "Work Mode": "نظام العمل",
    "Your CV and documents will be checked.": "سيتم فحص سيرتك الذاتية ومستنداتك.",
    "available role": "وظيفة متاحة",
    "position": "منصب",
    "published role": "وظيفة منشورة",
})

STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "01": "01",
    "02": "02",
    "About": "介绍",
    "Additional details": "其他详情",
    "All": "全部",
    "Application role": "申请职位",
    "Apply": "申请",
    "Apply before": "请在此日期前申请",
    "Apply for": "申请",
    "Apply online": "在线申请",
    "Attach certificates or licenses if they support the role.": "如与职位相关，请附上证书或执照。",
    "Back to Careers": "返回招聘",
    "Back to Job": "返回职位",
    "Candidate details": "候选人信息",
    "Certificates / education": "证书 / 教育背景",
    "Clear filters": "清除筛选",
    "Currently hiring": "正在招聘",
    "Details": "详情",
    "Documents": "文件",
    "Experience": "经验",
    "Featured": "精选",
    "General": "综合",
    "HR review": "人力资源审核",
    "Interview": "面试",
    "Interview invite": "面试邀请",
    "Invitation details will be sent by email.": "面试邀请详情将通过电子邮件发送。",
    "Job Application": "职位申请",
    "Job Opening": "职位空缺",
    "Job Type": "职位类型",
    "Job overview": "职位概览",
    "Make sure your email and phone number are correct.": "请确保您的邮箱和电话号码正确。",
    "Optional certificate/license · PDF/DOC/DOCX · max 8MB": "可选证书/执照 · PDF/DOC/DOCX · 最大 8MB",
    "Optional supporting document · PDF/DOC/DOCX · max 8MB": "可选支持文件 · PDF/DOC/DOCX · 最大 8MB",
    "Optional multiple files · PDF/DOC/DOCX · max 8MB each": "可选多个文件 · PDF/DOC/DOCX · 每个最大 8MB",
    "Personal information": "个人信息",
    "Positions": "招聘人数",
    "Preferred": "优先考虑",
    "Required · PDF/DOC/DOCX · max 8MB": "必填 · PDF/DOC/DOCX · 最大 8MB",
    "Reset search": "重置搜索",
    "Role summary": "职位摘要",
    "Search role, skill, job code, or location": "搜索职位、技能、职位编号或地点",
    "Selected applicants will be contacted.": "我们将联系入选申请人。",
    "Shortlist": "入围名单",
    "Shortlisted applicants will receive interview details by email.": "入围申请人将通过电子邮件收到面试详情。",
    "Showing": "显示",
    "Skills": "技能",
    "Submit for HR review": "提交给人力资源审核",
    "This information helps HR contact and evaluate the applicant correctly.": "这些信息有助于人力资源正确联系和评估申请人。",
    "Upload CV": "上传简历",
    "Upload a CV and any supporting documents that match the job requirements.": "上传简历以及符合职位要求的支持文件。",
    "Use PDF, DOC or DOCX files only.": "仅使用 PDF、DOC 或 DOCX 文件。",
    "What we need": "我们需要",
    "What you will do": "您将负责",
    "Work Mode": "工作模式",
    "Your CV and documents will be checked.": "我们将审核您的简历和文件。",
    "available role": "个可申请职位",
    "position": "职位",
    "published role": "个已发布职位",
})

# Leadership / CEO message labels.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Leadership Message": "كلمة القيادة",
    "Read Full Message": "قراءة الكلمة كاملة",
})

STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Leadership Message": "领导致辞",
    "Read Full Message": "阅读全文",
})

# Trust page certificate gallery labels.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Active": "سارية",
    "Certificate": "شهادة",
    "Certificate Details": "تفاصيل الشهادة",
    "Certificate image gallery": "معرض صور الشهادات",
    "Certificate image unavailable": "صورة الشهادة غير متوفرة",
    "Click any certificate to view it in full size with details.": "اضغط على أي شهادة لعرضها بالحجم الكامل مع التفاصيل.",
    "Close certificate preview": "إغلاق معاينة الشهادة",
    "Download file": "تحميل الملف",
    "Expired": "منتهية",
    "Expiry": "انتهاء الصلاحية",
    "View certificate": "عرض الشهادة",
    "View Full": "عرض كامل",
})

STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Active": "有效",
    "Certificate": "证书",
    "Certificate Details": "证书详情",
    "Certificate image gallery": "证书图片库",
    "Certificate image unavailable": "证书图片不可用",
    "Click any certificate to view it in full size with details.": "点击任意证书，可查看完整图片和详情。",
    "Close certificate preview": "关闭证书预览",
    "Download file": "下载文件",
    "Expired": "已过期",
    "Expiry": "到期日",
    "View certificate": "查看证书",
    "View Full": "查看完整",
})


# Trust framework section labels.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Verified credentials, organized for confidence.": "اعتمادات موثقة ومنظمة لتعزيز الثقة.",
    "Core vendor references and quality commitments are presented in a clean review-ready format.": "نعرض المراجع الأساسية والالتزامات بالجودة بصيغة واضحة وجاهزة للمراجعة.",
    "A focused view of the compliance references that support safe, dependable and quality-driven project delivery.": "عرض مركز لمراجع الامتثال التي تدعم تنفيذ المشاريع بأمان واعتمادية وجودة.",
})

STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Verified credentials, organized for confidence.": "以清晰结构展示认证资质，增强信任。",
    "Core vendor references and quality commitments are presented in a clean review-ready format.": "以便于审核的形式展示核心供应商资质和质量承诺。",
    "A focused view of the compliance references that support safe, dependable and quality-driven project delivery.": "集中展示支持安全、可靠和质量导向项目交付的合规依据。",
})


# Trust document / operational assurance labels.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Operational assurance, not just listed standards.": "ضمان تشغيلي وليس مجرد معايير معروضة.",
    "SESCCO connects every credential with practical site discipline, controlled execution and accountable delivery.": "تربط سيسكو كل اعتماد بانضباط ميداني عملي وتنفيذ منظم وتسليم مسؤول.",
    "Operational assurance principles": "مبادئ الضمان التشغيلي",
    "Supporting documents, ready when needed.": "مستندات داعمة جاهزة عند الحاجة.",
    "Public company files can be downloaded directly. Sensitive official documents can be marked request-only from admin.": "يمكن تحميل ملفات الشركة العامة مباشرة، ويمكن جعل المستندات الرسمية الحساسة متاحة بالطلب فقط من لوحة الإدارة.",
    "Download document": "تحميل المستند",
    "Request access": "طلب الوصول",
    "File will appear here after admin upload.": "سيظهر الملف هنا بعد رفعه من لوحة الإدارة.",
    "Version": "الإصدار",
    "Published": "تاريخ النشر",
})

STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Operational assurance, not just listed standards.": "不只是列出标准，更体现运营保障。",
    "SESCCO connects every credential with practical site discipline, controlled execution and accountable delivery.": "SESCCO 将每项资质与现场纪律、受控执行和负责交付相结合。",
    "Operational assurance principles": "运营保障原则",
    "Supporting documents, ready when needed.": "支持文件，随需可用。",
    "Public company files can be downloaded directly. Sensitive official documents can be marked request-only from admin.": "公开公司文件可直接下载；敏感官方文件可在后台设置为申请获取。",
    "Download document": "下载文件",
    "Request access": "申请访问",
    "File will appear here after admin upload.": "管理员上传后文件将在此显示。",
    "Version": "版本",
    "Published": "发布日期",
})



def static_text_id(text):
    return zlib.crc32(str(text).encode("utf-8"))


@register.simple_tag
def static_text(text):
    source_text = str(text)
    lang = get_language() or "en"
    object_id = static_text_id(source_text)
    override = LocalizedContent.objects.filter(
        content_type="statictext",
        object_id=object_id,
        language_code=lang,
        field_name="text",
    ).first()
    static_fallback = STATIC_TRANSLATIONS.get(lang, {}).get(source_text, source_text)
    if override and override.text and not _is_bad_demo_translation(override.text):
        override_text = str(override.text).strip()
        if lang != "en" and override_text == source_text.strip() and static_fallback != source_text:
            return mark_safe(static_fallback)
        return mark_safe(override.text)
    return static_fallback


# Upgrade 136 — visible multilingual home proof + static text coverage.
# These strings are used in CMS templates directly through `{% static_text %}`.
# Without explicit entries they remain English even on /ar/ and /zh-hans/ pages.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Practical engineering, construction and technical services delivered with safety, quality and reliable execution.": "خدمات هندسية وإنشائية وتقنية عملية تُنفذ باعتمادية مع الالتزام بالسلامة والجودة.",
    "A selected view of completed and ongoing works across industrial, commercial and infrastructure environments.": "عرض مختار لأعمال مكتملة وقيد التنفيذ ضمن البيئات الصناعية والتجارية والبنية التحتية.",
    "Trusted by respected organizations.": "موثوقون من قبل جهات مرموقة.",
    "We build long-term partnerships with organizations that value quality, safety, and engineering excellence.": "نبني شراكات طويلة الأمد مع جهات تقدّر الجودة والسلامة والتميز الهندسي.",
    "Trusted client logos slideshow": "عرض متحرك لشعارات العملاء الموثوقين",
    "View client": "عرض العميل",
    "No clients added yet.": "لم تتم إضافة عملاء بعد.",
    "Selected certificates.": "شهادات مختارة.",
    "A clean preview of key compliance documents that support SESCCO’s commitment to quality, safety, and dependable delivery.": "معاينة واضحة لأهم مستندات الامتثال التي تدعم التزام SESCCO بالجودة والسلامة والتسليم الموثوق.",
    "Certificate image gallery preview": "معاينة معرض صور الشهادات",
    "No certificates added yet.": "لم تتم إضافة شهادات بعد.",
    "Our Services": "خدماتنا",
    "View Our Projects": "عرض مشاريعنا",
    "Mission": "الرسالة",
    "Vision": "الرؤية",
    "To deliver dependable engineering and contracting solutions through safe execution, quality workmanship and practical project support.": "تقديم حلول هندسية ومقاولات موثوقة من خلال تنفيذ آمن وجودة عمل عالية ودعم عملي للمشاريع.",
    "To be recognized across Saudi Arabia as a trusted partner for integrated engineering, construction and support services.": "أن نكون شريكاً موثوقاً في المملكة العربية السعودية للخدمات الهندسية والإنشائية والدعم المتكامل.",
    "Click any certificate to view the full image and basic document details.": "اضغط على أي شهادة لعرض الصورة الكاملة وتفاصيل المستند الأساسية.",
    "View full image": "عرض الصورة كاملة",
    "Office Locations": "مواقع المكاتب",
    "Where to find us.": "أين تجدنا.",
    "Questions": "الأسئلة",
    "Project inquiry": "استفسار مشروع",
    "Contact methods": "وسائل التواصل",
    "New inquiry": "استفسار جديد",
    "Share your requirement and our team will contact you.": "شارك متطلباتك وسيتواصل معك فريقنا.",
    "Google map is not configured yet.": "خريطة Google غير مهيأة بعد.",
    "Add the Google Maps embed URL in Contact Page Settings.": "أضف رابط تضمين خرائط Google من إعدادات صفحة التواصل.",
    "Admin note": "ملاحظة للإدارة",
    "The map and directions link are controlled from Contact Page Settings in admin.": "يتم التحكم بالخريطة ورابط الاتجاهات من إعدادات صفحة التواصل في لوحة الإدارة.",
    "Need a similar project partner?": "هل تحتاج إلى شريك لمشروع مشابه؟",
    "Contact SESCCO to discuss your engineering or contracting requirements.": "تواصل مع SESCCO لمناقشة متطلباتك الهندسية أو التعاقدية.",
    "Try another keyword, status, year or category.": "جرّب كلمة مفتاحية أو حالة أو سنة أو فئة أخرى.",
    "Project Overview": "نظرة عامة على المشروع",
    "Key information and delivery details for this project.": "معلومات رئيسية وتفاصيل تنفيذ هذا المشروع.",
    "Project Description": "وصف المشروع",
    "Project description will be added from admin.": "سيتم إضافة وصف المشروع من لوحة الإدارة.",
    "Safety First": "السلامة أولاً",
    "Strict adherence to HSE standards with zero compromise.": "التزام صارم بمعايير السلامة والصحة والبيئة دون أي تهاون.",
    "Quality Assured": "جودة مضمونة",
    "Delivered to the highest engineering and quality standards.": "تم التنفيذ وفق أعلى معايير الهندسة والجودة.",
    "Delivered on Time": "تسليم في الوقت المحدد",
    "Completed within the planned schedule.": "اكتمل ضمن الجدول الزمني المخطط.",
    "Expert Team": "فريق خبير",
    "Experienced professionals ensuring reliable project delivery.": "متخصصون ذوو خبرة يضمنون تسليم المشروع باعتمادية.",
    "Key Deliverables": "المخرجات الرئيسية",
    "Search services": "البحث في الخدمات",
    "Search services, keywords...": "ابحث عن الخدمات أو الكلمات المفتاحية...",
    "Service category": "فئة الخدمة",
    "All Categories": "كل الفئات",
    "Sort services": "ترتيب الخدمات",
    "Default": "افتراضي",
    "Featured first": "المميزة أولاً",
    "A to Z": "من الألف إلى الياء",
    "Search": "بحث",
    "Try a different keyword or category.": "جرّب كلمة أو فئة مختلفة.",
})

STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Practical engineering, construction and technical services delivered with safety, quality and reliable execution.": "以安全、质量和可靠执行为核心，交付实用的工程、施工和技术服务。",
    "A selected view of completed and ongoing works across industrial, commercial and infrastructure environments.": "精选展示工业、商业和基础设施环境中的已完成及在建项目。",
    "Trusted by respected organizations.": "受到知名机构信赖。",
    "We build long-term partnerships with organizations that value quality, safety, and engineering excellence.": "我们与重视质量、安全和工程卓越的机构建立长期合作关系。",
    "Trusted client logos slideshow": "可信客户标识轮播",
    "View client": "查看客户",
    "No clients added yet.": "尚未添加客户。",
    "Selected certificates.": "精选证书。",
    "A clean preview of key compliance documents that support SESCCO’s commitment to quality, safety, and dependable delivery.": "清晰展示关键合规文件，体现 SESCCO 对质量、安全和可靠交付的承诺。",
    "Certificate image gallery preview": "证书图片库预览",
    "No certificates added yet.": "尚未添加证书。",
    "Our Services": "我们的服务",
    "View Our Projects": "查看项目",
    "Mission": "使命",
    "Vision": "愿景",
    "To deliver dependable engineering and contracting solutions through safe execution, quality workmanship and practical project support.": "通过安全执行、优质工艺和务实项目支持，交付可靠的工程与承包解决方案。",
    "To be recognized across Saudi Arabia as a trusted partner for integrated engineering, construction and support services.": "成为沙特阿拉伯综合工程、施工和支持服务领域值得信赖的合作伙伴。",
    "Click any certificate to view the full image and basic document details.": "点击任意证书查看完整图片和基本文件详情。",
    "View full image": "查看完整图片",
    "Office Locations": "办公室位置",
    "Where to find us.": "查找我们的位置。",
    "Questions": "问题",
    "Project inquiry": "项目咨询",
    "Contact methods": "联系方式",
    "New inquiry": "新咨询",
    "Share your requirement and our team will contact you.": "请说明您的需求，我们的团队会与您联系。",
    "Google map is not configured yet.": "Google 地图尚未配置。",
    "Add the Google Maps embed URL in Contact Page Settings.": "请在联系页面设置中添加 Google 地图嵌入链接。",
    "Admin note": "后台提示",
    "The map and directions link are controlled from Contact Page Settings in admin.": "地图和路线链接可在后台联系页面设置中管理。",
    "Need a similar project partner?": "需要类似项目合作伙伴？",
    "Contact SESCCO to discuss your engineering or contracting requirements.": "联系 SESCCO 讨论您的工程或承包需求。",
    "Try another keyword, status, year or category.": "请尝试其他关键词、状态、年份或类别。",
    "Project Overview": "项目概览",
    "Key information and delivery details for this project.": "该项目的关键信息和交付详情。",
    "Project Description": "项目描述",
    "Project description will be added from admin.": "项目描述将由后台添加。",
    "Safety First": "安全第一",
    "Strict adherence to HSE standards with zero compromise.": "严格遵守 HSE 标准，绝不妥协。",
    "Quality Assured": "质量保障",
    "Delivered to the highest engineering and quality standards.": "按照高水平工程和质量标准交付。",
    "Delivered on Time": "按时交付",
    "Completed within the planned schedule.": "在计划进度内完成。",
    "Expert Team": "专业团队",
    "Experienced professionals ensuring reliable project delivery.": "经验丰富的专业人员确保项目可靠交付。",
    "Key Deliverables": "主要交付内容",
    "Search services": "搜索服务",
    "Search services, keywords...": "搜索服务或关键词...",
    "Service category": "服务类别",
    "All Categories": "所有类别",
    "Sort services": "服务排序",
    "Default": "默认",
    "Featured first": "精选优先",
    "A to Z": "A 到 Z",
    "Search": "搜索",
    "Try a different keyword or category.": "请尝试其他关键词或类别。",
})


# Upgrade 139 — broad visible localization coverage for CMS cards, service list,
# project list, trust/compliance, careers and admin-like fallback labels.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Portfolio": "معرض الأعمال",
    "Trusted Delivery": "تسليم موثوق",
    "Built for leading companies and organizations.": "مصمم لخدمة الشركات والجهات الرائدة.",
    "Client logos are managed from the Clients module.": "تُدار شعارات العملاء من وحدة العملاء.",
    "Featured Service": "خدمة مميزة",
    "Explore Service": "استكشف الخدمة",
    "Our Approach": "منهجيتنا",
    "Built on a clear and proven process.": "منهجية واضحة ومجربة للتنفيذ.",
    "Service Questions": "أسئلة الخدمات",
    "What services does SESCCO provide?": "ما الخدمات التي تقدمها SESCCO؟",
    "SESCCO provides electrical engineering, civil and architectural fit-out works, contract support, electromechanical works and mechanical/fire-fighting services.": "تقدم SESCCO خدمات الهندسة الكهربائية والأعمال المدنية والتشطيبات المعمارية والدعم التعاقدي والأعمال الكهروميكانيكية والميكانيكية ومكافحة الحريق.",
    "Can SESCCO provide personnel and equipment support?": "هل يمكن لـ SESCCO توفير دعم الأفراد والمعدات؟",
    "Yes. Our contract support service provides qualified personnel and equipment support according to project needs.": "نعم، توفر خدمة الدعم التعاقدي لدينا كوادر مؤهلة ودعم معدات وفق احتياجات المشروع.",
    "Can these details be updated from admin?": "هل يمكن تحديث هذه التفاصيل من لوحة الإدارة؟",
    "Yes. This page and its custom CMS sections can be edited from the Django admin panel.": "نعم، يمكن تحرير هذه الصفحة وأقسامها المخصصة من لوحة إدارة Django.",
    "Search services": "البحث في الخدمات",
    "Search services, keywords...": "ابحث عن خدمة أو كلمة مفتاحية...",
    "Service category": "فئة الخدمة",
    "All Categories": "كل الفئات",
    "Sort services": "ترتيب الخدمات",
    "Default": "الافتراضي",
    "Featured first": "المميزة أولاً",
    "A to Z": "أ إلى ي",
    "Search": "بحث",
    "Service": "الخدمة",
    "Client s": "الشهادات",
    "Need a similar project partner?": "هل تحتاج إلى شريك لمشروع مشابه؟",
    "Contact SESCCO to discuss your engineering or contracting requirements.": "تواصل مع SESCCO لمناقشة متطلباتك الهندسية أو التعاقدية.",
    "Operational assurance, not just listed standards.": "ضمان تشغيلي وليس مجرد معايير معروضة.",
    "SESCCO connects every credential with practical site discipline, controlled execution and accountable delivery.": "تربط SESCCO كل اعتماد بانضباط ميداني عملي وتنفيذ مضبوط وتسليم مسؤول.",
    "Verified credentials, organized for confidence.": "اعتمادات موثقة ومنظمة لبناء الثقة.",
    "Core vendor references and quality commitments are presented in a clean review-ready format.": "تُعرض مراجع الموردين الأساسية والتزامات الجودة بصيغة منظمة وجاهزة للمراجعة.",
    "A focused view of the compliance references that support safe, dependable and quality-driven project delivery.": "عرض مركز لمراجع الامتثال التي تدعم تسليم المشاريع بأمان واعتمادية وجودة.",
    "Full-time": "دوام كامل",
    "Part-time": "دوام جزئي",
    "Contract": "عقد",
    "Temporary": "مؤقت",
    "Internship": "تدريب",
    "Site Based": "ميداني",
    "Office Based": "مكتبي",
    "Hybrid": "هجين",
    "Remote": "عن بُعد",
    "Entry Level": "مبتدئ",
    "Junior": "مستوى أول",
    "Mid Level": "مستوى متوسط",
    "Senior": "متقدم",
    "Lead / Supervisor": "قائد / مشرف",
    "Manager": "مدير",
    "Skills": "المهارات",
    "Role summary": "ملخص الدور",
    "Benefits / Notes": "المزايا / ملاحظات",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Portfolio": "项目组合",
    "Trusted Delivery": "可靠交付",
    "Built for leading companies and organizations.": "面向领先企业和机构而构建。",
    "Client logos are managed from the Clients module.": "客户标志由客户模块管理。",
    "Featured Service": "精选服务",
    "Explore Service": "查看服务",
    "Our Approach": "我们的方法",
    "Built on a clear and proven process.": "基于清晰且经过验证的流程。",
    "Service Questions": "服务问题",
    "What services does SESCCO provide?": "SESCCO 提供哪些服务？",
    "SESCCO provides electrical engineering, civil and architectural fit-out works, contract support, electromechanical works and mechanical/fire-fighting services.": "SESCCO 提供电气工程、土建与建筑装修、合同支持、机电工程以及机械/消防服务。",
    "Can SESCCO provide personnel and equipment support?": "SESCCO 能提供人员和设备支持吗？",
    "Yes. Our contract support service provides qualified personnel and equipment support according to project needs.": "可以。我们的合同支持服务可根据项目需求提供合格人员和设备支持。",
    "Can these details be updated from admin?": "这些信息可以在后台更新吗？",
    "Yes. This page and its custom CMS sections can be edited from the Django admin panel.": "可以。本页面及其自定义 CMS 区块可在 Django 后台编辑。",
    "Search services": "搜索服务",
    "Search services, keywords...": "搜索服务或关键词...",
    "Service category": "服务类别",
    "All Categories": "所有类别",
    "Sort services": "服务排序",
    "Default": "默认",
    "Featured first": "精选优先",
    "A to Z": "A 到 Z",
    "Search": "搜索",
    "Service": "服务",
    "Client s": "认证",
    "Need a similar project partner?": "需要类似项目合作伙伴吗？",
    "Contact SESCCO to discuss your engineering or contracting requirements.": "联系 SESCCO 讨论您的工程或承包需求。",
    "Operational assurance, not just listed standards.": "运营保障，而不仅是列出的标准。",
    "SESCCO connects every credential with practical site discipline, controlled execution and accountable delivery.": "SESCCO 将每项资质与现场纪律、受控执行和责任交付相结合。",
    "Verified credentials, organized for confidence.": "已验证资质，组织清晰，增强信任。",
    "Core vendor references and quality commitments are presented in a clean review-ready format.": "核心供应商资质和质量承诺以清晰、便于审核的形式呈现。",
    "A focused view of the compliance references that support safe, dependable and quality-driven project delivery.": "集中展示支持安全、可靠和质量驱动交付的合规依据。",
    "Full-time": "全职",
    "Part-time": "兼职",
    "Contract": "合同制",
    "Temporary": "临时",
    "Internship": "实习",
    "Site Based": "现场工作",
    "Office Based": "办公室工作",
    "Hybrid": "混合办公",
    "Remote": "远程",
    "Entry Level": "入门级",
    "Junior": "初级",
    "Mid Level": "中级",
    "Senior": "高级",
    "Lead / Supervisor": "负责人 / 主管",
    "Manager": "经理",
    "Skills": "技能",
    "Role summary": "职位摘要",
    "Benefits / Notes": "福利 / 备注",
})
VISIBLE_CMS_FALLBACK_TRANSLATIONS.setdefault("ar", {}).update({
    "Project Categories": "فئات المشاريع",
    "Core Service Areas": "مجالات الخدمة الأساسية",
    "Vendor Codes": "رموز الموردين",
    "Years of Trust": "سنوات من الثقة",
    "Requirement review": "مراجعة المتطلبات",
    "We review scope, drawings, schedule and site needs before execution.": "نراجع النطاق والرسومات والجدول واحتياجات الموقع قبل التنفيذ.",
    "Resource planning": "تخطيط الموارد",
    "We plan project teams, equipment and coordination requirements.": "نخطط متطلبات فرق المشروع والمعدات والتنسيق.",
    "Safe execution": "تنفيذ آمن",
    "Work is executed with safety, quality and client coordination.": "يتم تنفيذ العمل مع الالتزام بالسلامة والجودة والتنسيق مع العميل.",
    "Close-out support": "دعم الإغلاق والتسليم",
    "We support handover, records and follow-up where required.": "ندعم التسليم والسجلات والمتابعة عند الحاجة.",
    "Safety": "السلامة",
    "We prioritize safe work practices and protection of people and the environment.": "نولي أولوية لممارسات العمل الآمنة وحماية الأفراد والبيئة.",
    "Quality": "الجودة",
    "We focus on meeting project requirements and client expectations.": "نركز على تلبية متطلبات المشروع وتوقعات العميل.",
    "Quality Management": "إدارة الجودة",
    "Quality-focused execution supported by controlled processes and dependable service delivery.": "تنفيذ يركز على الجودة ويدعمه ضبط العمليات وتسليم موثوق للخدمات.",
    "Environmental Responsibility": "المسؤولية البيئية",
    "Work practices are guided by responsible site coordination and environmental awareness.": "تسترشد ممارسات العمل بتنسيق موقعي مسؤول ووعي بيئي.",
    "Occupational Health & Safety": "الصحة والسلامة المهنية",
    "Safety-led planning, workforce awareness and site discipline support safer project execution.": "يساعد التخطيط القائم على السلامة ووعي القوى العاملة وانضباط الموقع على تنفيذ أكثر أماناً.",
    "Saudi Aramco Vendor Code": "رمز مورد أرامكو السعودية",
    "SESCCO vendor code: 10114560.": "رمز مورد SESCCO: 10114560.",
    "Saudi Electricity Company Vendor Code": "رمز مورد الشركة السعودية للكهرباء",
    "SESCCO SEC vendor code: 02013075.": "رمز مورد SESCCO لدى SEC: 02013075.",
    "Verified Compliance Records": "سجلات امتثال موثقة",
    "Vendor references and supporting documents are organized for review-ready confidence.": "تم تنظيم مراجع الموردين والمستندات الداعمة لتكون جاهزة للمراجعة بثقة.",
    "Long-Term Partnership": "شراكة طويلة الأمد",
    "We focus on creating value for clients through professionalism and quality services.": "نركز على خلق قيمة للعملاء من خلال الاحترافية والخدمات عالية الجودة.",
    "Relevant safety certificate preferred": "يفضل وجود شهادة سلامة ذات صلة",
    "Knowledge of site safety documentation": "معرفة بتوثيق السلامة في الموقع",
    "Ability to communicate with workers and supervisors": "القدرة على التواصل مع العمال والمشرفين",
    "Inspection reporting": "إعداد تقارير التفتيش",
    "Toolbox talk support": "دعم اجتماعات التوعية اليومية",
    "Incident documentation": "توثيق الحوادث",
    "Corrective action follow-up": "متابعة الإجراءات التصحيحية",
})
VISIBLE_CMS_FALLBACK_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Project Categories": "项目类别",
    "Core Service Areas": "核心服务领域",
    "Vendor Codes": "供应商代码",
    "Years of Trust": "信任年限",
    "Requirement review": "需求审核",
    "We review scope, drawings, schedule and site needs before execution.": "执行前审核范围、图纸、计划和现场需求。",
    "Resource planning": "资源规划",
    "We plan project teams, equipment and coordination requirements.": "规划项目团队、设备和协调需求。",
    "Safe execution": "安全执行",
    "Work is executed with safety, quality and client coordination.": "在安全、质量和客户协调下执行工作。",
    "Close-out support": "收尾支持",
    "We support handover, records and follow-up where required.": "按需支持移交、记录和后续跟进。",
    "Safety": "安全",
    "We prioritize safe work practices and protection of people and the environment.": "我们优先考虑安全作业实践以及人员和环境保护。",
    "Quality": "质量",
    "We focus on meeting project requirements and client expectations.": "我们专注满足项目要求和客户期望。",
    "Quality Management": "质量管理",
    "Quality-focused execution supported by controlled processes and dependable service delivery.": "以质量为核心的执行，由受控流程和可靠服务交付支持。",
    "Environmental Responsibility": "环境责任",
    "Work practices are guided by responsible site coordination and environmental awareness.": "工作实践以负责任的现场协调和环保意识为指导。",
    "Occupational Health & Safety": "职业健康与安全",
    "Safety-led planning, workforce awareness and site discipline support safer project execution.": "以安全为导向的规划、员工意识和现场纪律支持更安全的项目执行。",
    "Saudi Aramco Vendor Code": "沙特阿美供应商代码",
    "SESCCO vendor code: 10114560.": "SESCCO 供应商代码：10114560。",
    "Saudi Electricity Company Vendor Code": "沙特电力公司供应商代码",
    "SESCCO SEC vendor code: 02013075.": "SESCCO SEC 供应商代码：02013075。",
    "Verified Compliance Records": "已验证合规记录",
    "Vendor references and supporting documents are organized for review-ready confidence.": "供应商资质和支持文件组织清晰，便于审核。",
    "Long-Term Partnership": "长期合作伙伴关系",
    "We focus on creating value for clients through professionalism and quality services.": "我们通过专业精神和优质服务为客户创造价值。",
    "Relevant safety certificate preferred": "优先考虑相关安全证书",
    "Knowledge of site safety documentation": "了解现场安全文件",
    "Ability to communicate with workers and supervisors": "能够与工人和主管沟通",
    "Inspection reporting": "检查报告",
    "Toolbox talk support": "班前安全会支持",
    "Incident documentation": "事故记录",
    "Corrective action follow-up": "纠正措施跟进",
})


# Upgrade 143 — remaining visible Arabic localization polish and HTML-rich-text fallback coverage.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "About This Service": "عن هذه الخدمة",
    "Service Summary": "ملخص الخدمة",
    "Featured": "مميزة",
    "Yes": "نعم",
    "No": "لا",
    "General": "عام",
    "Brochure available": "الكتيب متاح",
    "What We Deliver": "ما نقدمه",
    "Structured deliverables for this service": "مخرجات منظمة لهذه الخدمة",
    "Related Projects": "مشاريع ذات صلة",
    "See how this service is applied in real work.": "شاهد كيف تُطبق هذه الخدمة في أعمال فعلية.",
    "Explore similar work.": "استكشف أعمالاً مشابهة.",
    "Detailed Scope": "النطاق التفصيلي",
    "Category": "الفئة",
    "Year": "السنة",
    "Months": "الأشهر",
    "Location": "الموقع",
    "Download Brochure": "تحميل الكتيب",
    "Request a Quote": "طلب عرض سعر",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "About This Service": "关于此服务",
    "Service Summary": "服务摘要",
    "Featured": "精选",
    "Yes": "是",
    "No": "否",
    "General": "通用",
    "Brochure available": "可下载资料",
    "What We Deliver": "我们交付的内容",
    "Structured deliverables for this service": "本服务的结构化交付内容",
    "Related Projects": "相关项目",
    "See how this service is applied in real work.": "查看该服务如何应用于实际项目。",
    "Explore similar work.": "探索类似项目。",
    "Detailed Scope": "详细范围",
    "Category": "类别",
    "Year": "年份",
    "Months": "月份",
    "Location": "位置",
    "Download Brochure": "下载资料",
    "Request a Quote": "请求报价",
})
VISIBLE_CMS_FALLBACK_TRANSLATIONS.setdefault("ar", {}).update({
    "SESCCO provides electrical engineering, civil and architectural fit-out works, contract support, electromechanical works and mechanical/fire-fighting services.": "تقدم SESCCO خدمات الهندسة الكهربائية والأعمال المدنية والتشطيبات المعمارية والدعم التعاقدي والأعمال الكهروميكانيكية والميكانيكية ومكافحة الحريق.",
    "Yes. This page and its custom CMS sections can be edited from the Django admin panel.": "نعم، يمكن تحرير هذه الصفحة وأقسامها المخصصة من لوحة إدارة Django.",
    "What services does SESCCO provide?": "ما الخدمات التي تقدمها SESCCO؟",
    "Can these details be updated from admin?": "هل يمكن تحديث هذه التفاصيل من لوحة الإدارة؟",
})
VISIBLE_CMS_FALLBACK_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "SESCCO provides electrical engineering, civil and architectural fit-out works, contract support, electromechanical works and mechanical/fire-fighting services.": "SESCCO 提供电气工程、土建与建筑装修、合同支持、机电工程以及机械/消防服务。",
    "Yes. This page and its custom CMS sections can be edited from the Django admin panel.": "可以。本页面及其自定义 CMS 区块可在 Django 后台编辑。",
    "What services does SESCCO provide?": "SESCCO 提供哪些服务？",
    "Can these details be updated from admin?": "这些信息可以在后台更新吗？",
})

STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "The Challenge": "التحدي",
    "Our Scope": "نطاق عملنا",
    "Our Solution": "حلنا",
    "Key Outcomes": "النتائج الرئيسية",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "The Challenge": "挑战",
    "Our Scope": "我们的范围",
    "Our Solution": "我们的解决方案",
    "Key Outcomes": "关键成果",
})

# Upgrade 155 — project CTA premium card static translations
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Contact SESCCO to discuss your engineering or contracting requirements. Our team is ready to deliver solutions that perform.": "تواصل مع SESCCO لمناقشة متطلباتك الهندسية أو التعاقدية. فريقنا جاهز لتقديم حلول عملية موثوقة.",
    "Trusted Expertise": "خبرة موثوقة",
    "Proven experience across diverse industries.": "خبرة مثبتة عبر قطاعات متعددة.",
    "Collaborative Approach": "نهج تعاوني",
    "Working closely with you to achieve your goals.": "نعمل معك عن قرب لتحقيق أهدافك.",
    "End-to-End Support": "دعم شامل",
    "From planning to execution and beyond.": "من التخطيط إلى التنفيذ وما بعده.",
    "Safety & Quality First": "السلامة والجودة أولاً",
    "Committed to the highest standards in every project.": "ملتزمون بأعلى المعايير في كل مشروع.",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Contact SESCCO to discuss your engineering or contracting requirements. Our team is ready to deliver solutions that perform.": "联系 SESCCO 讨论您的工程或承包需求。我们的团队已准备好提供可靠高效的解决方案。",
    "Trusted Expertise": "可信专业能力",
    "Proven experience across diverse industries.": "在多个行业拥有成熟经验。",
    "Collaborative Approach": "协作式方法",
    "Working closely with you to achieve your goals.": "与您紧密合作，实现项目目标。",
    "End-to-End Support": "端到端支持",
    "From planning to execution and beyond.": "从规划到执行及后续支持。",
    "Safety & Quality First": "安全与质量优先",
    "Committed to the highest standards in every project.": "每个项目都坚持高标准交付。",
})

# Upgrade 156 — project client proof slider and project-specific CTA copy.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Our project experience is supported by long-term relationships with respected clients and industrial organizations.": "تدعم خبرتنا في المشاريع علاقات طويلة الأمد مع عملاء وجهات صناعية موثوقة.",
    "Project Delivery": "تنفيذ المشاريع",
    "Looking for dependable project execution?": "هل تبحث عن تنفيذ موثوق لمشروعك؟",
    "SESCCO supports project owners and contractors with organized engineering, safe site execution and reliable handover support.": "تدعم SESCCO ملاك المشاريع والمقاولين بخدمات هندسية منظمة وتنفيذ ميداني آمن ودعم موثوق للتسليم.",
    "Discuss Your Project": "ناقش مشروعك",
    "Proven Delivery": "تنفيذ مثبت",
    "Project experience across industrial, utility and commercial sites.": "خبرة مشاريع في المواقع الصناعية والخدمية والتجارية.",
    "Client Coordination": "تنسيق مع العميل",
    "Clear communication from requirement review to close-out.": "تواصل واضح من مراجعة المتطلبات حتى الإغلاق.",
    "Execution Support": "دعم التنفيذ",
    "Project teams, technical coordination and site follow-up.": "فرق مشاريع وتنسيق فني ومتابعة ميدانية.",
    "Safety & Quality": "السلامة والجودة",
    "Work delivered with controlled processes and responsible supervision.": "أعمال تُنفذ بإجراءات مضبوطة وإشراف مسؤول.",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Our project experience is supported by long-term relationships with respected clients and industrial organizations.": "我们的项目经验建立在与受尊重客户和工业机构的长期合作关系之上。",
    "Project Delivery": "项目交付",
    "Looking for dependable project execution?": "正在寻找可靠的项目执行支持？",
    "SESCCO supports project owners and contractors with organized engineering, safe site execution and reliable handover support.": "SESCCO 为项目业主和承包商提供有序工程、安全现场执行和可靠交接支持。",
    "Discuss Your Project": "讨论您的项目",
    "Proven Delivery": "成熟交付",
    "Project experience across industrial, utility and commercial sites.": "具备工业、公用事业和商业现场项目经验。",
    "Client Coordination": "客户协调",
    "Clear communication from requirement review to close-out.": "从需求审查到收尾保持清晰沟通。",
    "Execution Support": "执行支持",
    "Project teams, technical coordination and site follow-up.": "项目团队、技术协调和现场跟进。",
    "Safety & Quality": "安全与质量",
    "Work delivered with controlled processes and responsible supervision.": "以受控流程和负责监督完成工作。",
})

# Upgrade 164 — certificate modal localization coverage.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Certificate type": "نوع الشهادة",
    "Issued by": "جهة الإصدار",
    "Description": "الوصف",
    "Click any certificate to view the full image and basic document details.": "اضغط على أي شهادة لعرض الصورة الكاملة وتفاصيل المستند الأساسية.",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Certificate type": "证书类型",
    "Issued by": "颁发机构",
    "Description": "说明",
    "Click any certificate to view the full image and basic document details.": "点击任意证书，查看完整图片和基本文件详情。",
})

VISIBLE_CMS_FALLBACK_TRANSLATIONS.setdefault("ar", {}).update({
    "Environmental Management": "إدارة البيئة",
    "Quality management system certification for engineering, procurement, construction, testing and commissioning services.": "شهادة نظام إدارة الجودة لخدمات الهندسة والتوريد والإنشاء والاختبار والتشغيل التجريبي.",
    "Environmental management system certification reflecting responsible operational and site coordination practices.": "شهادة نظام الإدارة البيئية التي تعكس ممارسات تشغيلية مسؤولة وتنسيقاً منضبطاً في الموقع.",
    "Occupational health and safety management certification supporting safer workplaces and disciplined project execution.": "شهادة إدارة الصحة والسلامة المهنية الداعمة لبيئات عمل أكثر أماناً وتنفيذ مشاريع أكثر انضباطاً.",
    "Cybersecurity Compliance Certificate": "شهادة الامتثال للأمن السيبراني",
    "Saudi Aramco third-party cybersecurity compliance certificate assessed against the SACS-002 standard.": "شهادة امتثال للأمن السيبراني من طرف ثالث لأرامكو السعودية، تم تقييمها وفق معيار SACS-002.",
    "ISO Certifications": "شهادات ISO",
    "Quality, environmental, health & safety and cybersecurity compliance certifications.": "شهادات الجودة والبيئة والصحة والسلامة والامتثال للأمن السيبراني.",
})
VISIBLE_CMS_FALLBACK_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Environmental Management": "环境管理",
    "Quality management system certification for engineering, procurement, construction, testing and commissioning services.": "质量管理体系认证，覆盖工程、采购、施工、测试和调试服务。",
    "Environmental management system certification reflecting responsible operational and site coordination practices.": "环境管理体系认证，体现负责任的运营和现场协调实践。",
    "Occupational health and safety management certification supporting safer workplaces and disciplined project execution.": "职业健康与安全管理认证，支持更安全的工作场所和规范的项目执行。",
    "Cybersecurity Compliance Certificate": "网络安全合规证书",
    "Saudi Aramco third-party cybersecurity compliance certificate assessed against the SACS-002 standard.": "沙特阿美第三方网络安全合规证书，依据 SACS-002 标准评估。",
    "ISO Certifications": "ISO 认证",
    "Quality, environmental, health & safety and cybersecurity compliance certifications.": "质量、环境、职业健康安全和网络安全合规认证。",
})

# Upgrade 165 — full service/project detail static localization sweep.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Download Brochure": "تحميل البروشور",
    "Download the service brochure, capability reference or company profile document for this service.": "حمّل بروشور الخدمة أو مرجع القدرات أو ملف الشركة الخاص بهذه الخدمة.",
    "Download Capability PDF": "تحميل ملف القدرات PDF",
    "Request Document": "طلب المستند",
    "Have a Project in Mind?": "هل لديك مشروع في ذهنك؟",
    "Talk to our experts and let’s build the right solution for your business.": "تحدث مع خبرائنا لنضع الحل المناسب لأعمالك.",
    "Get in Touch": "تواصل معنا",
    "Project Documents": "مستندات المشروع",
    "Download project-related files, case studies or capability references.": "حمّل ملفات المشروع أو دراسات الحالة أو مراجع القدرات ذات الصلة.",
    "Download Project Profile": "تحميل ملف المشروع",
    "Interested in a similar project?": "هل لديك مشروع مشابه؟",
    "Talk to our team about your project requirements.": "تحدث مع فريقنا حول متطلبات مشروعك.",
    "Start a Project": "ابدأ مشروعاً",
    "Service Features": "مميزات الخدمة",
    "Our Process": "آلية العمل",
    "How we deliver this service.": "كيف ننفذ هذه الخدمة.",
    "No related projects yet.": "لا توجد مشاريع مرتبطة حالياً.",
    "Related Projects": "مشاريع ذات صلة",
    "Explore similar work.": "استعرض أعمالاً مشابهة.",
    "See how this service is applied in real work.": "شاهد كيف تُطبق هذه الخدمة في الأعمال الواقعية.",
    "View Project Details": "عرض تفاصيل المشروع",
    "All Projects": "كل المشاريع",
    "Search by project, client, contractor, location, scope...": "ابحث حسب المشروع أو العميل أو المقاول أو الموقع أو النطاق...",
    "All statuses": "كل الحالات",
    "Completed": "مكتمل",
    "Complete": "مكتمل",
    "Ongoing": "قيد التنفيذ",
    "Planned": "مخطط",
    "All years": "كل السنوات",
    "Newest first": "الأحدث أولاً",
    "Oldest first": "الأقدم أولاً",
    "Default order": "الترتيب الافتراضي",
    "Clear": "مسح",
    "Project Metrics": "مؤشرات المشروع",
    "Location": "الموقع",
    "Status": "الحالة",
    "Duration": "المدة",
    "Year": "السنة",
    "Client": "العميل",
    "Contractor": "المقاول",
    "Category": "الفئة",
    "Project Overview": "نظرة عامة على المشروع",
    "Project Description": "وصف المشروع",
    "Project at a Glance": "لمحة عن المشروع",
    "Project description will be added from admin.": "سيتم إضافة وصف المشروع من لوحة الإدارة.",
    "Key information and delivery details for this project.": "معلومات رئيسية وتفاصيل تنفيذ هذا المشروع.",
    "Key Deliverables": "المخرجات الرئيسية",
    "The Challenge": "التحدي",
    "Our Scope": "نطاق عملنا",
    "Our Solution": "حلنا",
    "Key Outcomes": "النتائج الرئيسية",
    "Detailed Scope": "النطاق التفصيلي",
    "Safety First": "السلامة أولاً",
    "Strict adherence to HSE standards with zero compromise.": "التزام صارم بمعايير السلامة دون أي تهاون.",
    "Quality Assured": "جودة مضمونة",
    "Delivered to the highest engineering and quality standards.": "تنفيذ وفق أعلى معايير الهندسة والجودة.",
    "Delivered on Time": "التسليم في الوقت المحدد",
    "Completed within the planned schedule.": "اكتمل ضمن الجدول الزمني المخطط.",
    "Expert Team": "فريق خبير",
    "Experienced professionals ensuring reliable project delivery.": "مختصون ذوو خبرة يضمنون تسليم المشروع باعتمادية.",
    "Home": "الرئيسية",
    "Services": "الخدمات",
    "Projects": "المشاريع",
    "About Us": "من نحن",
    "Quick Links": "روابط سريعة",
    "Showing 1 matching project.": "يتم عرض مشروع مطابق واحد.",
    "Showing {count} matching projects.": "يتم عرض {count} مشاريع مطابقة.",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Download Brochure": "下载宣传册",
    "Download the service brochure, capability reference or company profile document for this service.": "下载此服务的宣传册、能力参考或公司简介文件。",
    "Download Capability PDF": "下载能力 PDF",
    "Request Document": "申请文件",
    "Have a Project in Mind?": "有项目需求？",
    "Talk to our experts and let’s build the right solution for your business.": "与我们的专家沟通，为您的业务制定合适方案。",
    "Get in Touch": "联系我们",
    "Project Documents": "项目文件",
    "Download project-related files, case studies or capability references.": "下载项目相关文件、案例研究或能力参考。",
    "Download Project Profile": "下载项目资料",
    "Interested in a similar project?": "需要类似项目支持？",
    "Talk to our team about your project requirements.": "请与我们的团队沟通您的项目需求。",
    "Start a Project": "启动项目",
    "Service Features": "服务特点",
    "Our Process": "服务流程",
    "How we deliver this service.": "我们如何交付此服务。",
    "No related projects yet.": "暂无相关项目。",
    "Related Projects": "相关项目",
    "Explore similar work.": "浏览类似案例。",
    "See how this service is applied in real work.": "了解此服务如何应用于实际项目。",
    "View Project Details": "查看项目详情",
    "All Projects": "全部项目",
    "Search by project, client, contractor, location, scope...": "按项目、客户、承包商、地点或范围搜索...",
    "All statuses": "全部状态",
    "Completed": "已完成",
    "Complete": "已完成",
    "Ongoing": "进行中",
    "Planned": "计划中",
    "All years": "全部年份",
    "Newest first": "最新优先",
    "Oldest first": "最早优先",
    "Default order": "默认顺序",
    "Clear": "清除",
    "Project Metrics": "项目指标",
    "Location": "地点",
    "Status": "状态",
    "Duration": "周期",
    "Year": "年份",
    "Client": "客户",
    "Contractor": "承包商",
    "Category": "类别",
    "Project Overview": "项目概览",
    "Project Description": "项目说明",
    "Project at a Glance": "项目概况",
    "Project description will be added from admin.": "项目说明将由管理员添加。",
    "Key information and delivery details for this project.": "本项目的关键信息和交付详情。",
    "Key Deliverables": "关键交付内容",
    "The Challenge": "挑战",
    "Our Scope": "我们的范围",
    "Our Solution": "我们的方案",
    "Key Outcomes": "主要成果",
    "Detailed Scope": "详细范围",
    "Safety First": "安全优先",
    "Strict adherence to HSE standards with zero compromise.": "严格遵守 HSE 标准，绝不妥协。",
    "Quality Assured": "质量保障",
    "Delivered to the highest engineering and quality standards.": "按照高工程和质量标准交付。",
    "Delivered on Time": "按时交付",
    "Completed within the planned schedule.": "按计划周期完成。",
    "Expert Team": "专业团队",
    "Experienced professionals ensuring reliable project delivery.": "经验丰富的专业人员确保可靠交付。",
    "Home": "首页",
    "Services": "服务",
    "Projects": "项目",
    "About Us": "关于我们",
    "Quick Links": "快速链接",
    "Showing 1 matching project.": "显示 1 个匹配项目。",
    "Showing {count} matching projects.": "显示 {count} 个匹配项目。",
})
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Learn More About Us": "تعرف علينا أكثر",
    "Saudi Arabia Based": "مقرنا في السعودية",
    "Established": "تأسست",
    "SEC Vendor Code": "رمز مورد SEC",
    "Aramco Vendor Code": "رمز مورد أرامكو",
    "Trusted Clients": "عملاء موثوقون",
    "Certifications": "الشهادات",
    "Add Why Choose Items and enable show on about.": "أضف عناصر لماذا تختارنا وفعل عرضها في صفحة من نحن.",
    "Add timeline items from Django admin.": "أضف عناصر الجدول الزمني من لوحة إدارة Django.",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Learn More About Us": "进一步了解我们",
    "Saudi Arabia Based": "位于沙特阿拉伯",
    "Established": "成立于",
    "SEC Vendor Code": "SEC 供应商代码",
    "Aramco Vendor Code": "阿美供应商代码",
    "Trusted Clients": "可信客户",
    "Certifications": "认证",
    "Add Why Choose Items and enable show on about.": "请添加“为什么选择我们”项目，并启用在关于页面显示。",
    "Add timeline items from Django admin.": "请从 Django 管理后台添加时间线项目。",
})
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Careers": "الوظائف",
    "Contact": "اتصل بنا",
    "Contact Us": "اتصل بنا",
    "Open Jobs": "الوظائف المتاحة",
    "Apply Online": "التقديم عبر الإنترنت",
    "Contact HR": "تواصل مع الموارد البشرية",
    "Connect": "تواصل",
    "Open SESCCO location in Google Maps": "فتح موقع SESCCO في خرائط Google",
    "Primary navigation": "التنقل الرئيسي",
    "Open": "فتح",
    "Certificates": "الشهادات",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Careers": "招聘",
    "Contact": "联系",
    "Contact Us": "联系我们",
    "Open Jobs": "开放职位",
    "Apply Online": "在线申请",
    "Contact HR": "联系人力资源",
    "Connect": "联系",
    "Open SESCCO location in Google Maps": "在 Google 地图中打开 SESCCO 位置",
    "Primary navigation": "主导航",
    "Open": "打开",
    "Certificates": "认证",
})
STATIC_TRANSLATIONS.setdefault("ar", {}).update({"Open menu": "فتح القائمة"})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({"Open menu": "打开菜单"})
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "6 Months (June 2025)": "6 أشهر (يونيو 2025)",
    "7 Months (April 2026)": "7 أشهر (أبريل 2026)",
    "8 Months (April 2025)": "8 أشهر (أبريل 2025)",
    "8 Months (May 2025)": "8 أشهر (مايو 2025)",
    "6 Months (July 2025)": "6 أشهر (يوليو 2025)",
    "Completed May 2025": "اكتمل في مايو 2025",
    "12 Months (Completed June 2023)": "12 شهراً (اكتمل في يونيو 2023)",
    "18 Months (Completed October 2024)": "18 شهراً (اكتمل في أكتوبر 2024)",
    "Starting 2025/2026": "بدأ في 2025/2026",
    "Completed October 2016": "اكتمل في أكتوبر 2016",
    "Completed August 2016": "اكتمل في أغسطس 2016",
    "Project Completed": "المشروع مكتمل",
    "Saudi Arabia": "المملكة العربية السعودية",
    "Yanbu, Saudi Arabia": "ينبع، المملكة العربية السعودية",
    "Jubail, Saudi Arabia": "الجبيل، المملكة العربية السعودية",
    "Jafurah, Saudi Arabia": "الجافورة، المملكة العربية السعودية",
    "Riyadh, Saudi Arabia": "الرياض، المملكة العربية السعودية",
    "Haradh, Saudi Arabia": "حرض، المملكة العربية السعودية",
    "Al Khobar, Saudi Arabia": "الخبر، المملكة العربية السعودية",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "6 Months (June 2025)": "6 个月（2025 年 6 月）",
    "7 Months (April 2026)": "7 个月（2026 年 4 月）",
    "8 Months (April 2025)": "8 个月（2025 年 4 月）",
    "8 Months (May 2025)": "8 个月（2025 年 5 月）",
    "6 Months (July 2025)": "6 个月（2025 年 7 月）",
    "Completed May 2025": "2025 年 5 月完成",
    "12 Months (Completed June 2023)": "12 个月（2023 年 6 月完成）",
    "18 Months (Completed October 2024)": "18 个月（2024 年 10 月完成）",
    "Starting 2025/2026": "2025/2026 年开始",
    "Completed October 2016": "2016 年 10 月完成",
    "Completed August 2016": "2016 年 8 月完成",
    "Project Completed": "项目已完成",
    "Saudi Arabia": "沙特阿拉伯",
    "Yanbu, Saudi Arabia": "延布，沙特阿拉伯",
    "Jubail, Saudi Arabia": "朱拜勒，沙特阿拉伯",
    "Jafurah, Saudi Arabia": "贾富拉，沙特阿拉伯",
    "Riyadh, Saudi Arabia": "利雅得，沙特阿拉伯",
    "Haradh, Saudi Arabia": "哈拉德，沙特阿拉伯",
    "Al Khobar, Saudi Arabia": "胡拜尔，沙特阿拉伯",
})
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "No featured services added yet.": "لم تتم إضافة خدمات مميزة بعد.",
    "No featured projects added yet.": "لم تتم إضافة مشاريع مميزة بعد.",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "No featured services added yet.": "暂无精选服务。",
    "No featured projects added yet.": "暂无精选项目。",
})

# Upgrade 166 — remaining visible localization for career/contact forms and JS messages.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Profile review": "مراجعة الملف",
    "Upload documents": "رفع المستندات",
    "Verify email separately": "التحقق من البريد بشكل منفصل",
    "Email verification": "التحقق من البريد الإلكتروني",
    "Verify your email before submitting your application.": "تحقق من بريدك الإلكتروني قبل إرسال الطلب.",
    "Please verify this email before submitting the application.": "يرجى التحقق من هذا البريد الإلكتروني قبل إرسال الطلب.",
    "Not verified": "غير موثق",
    "Verified": "موثق",
    "Verify Email": "تحقق من البريد",
    "Secure check": "تحقق آمن",
    "Verify your email": "تحقق من بريدك الإلكتروني",
    "We will send a 6-digit code to your email. After successful verification, the submit button will unlock automatically.": "سنرسل رمزاً من 6 أرقام إلى بريدك الإلكتروني. بعد التحقق بنجاح سيتم تفعيل زر الإرسال تلقائياً.",
    "Verification email": "بريد التحقق",
    "Send Code": "إرسال الرمز",
    "Cancel": "إلغاء",
    "Submit application": "إرسال الطلب",
    "After your email is marked verified, submit the final application for HR review.": "بعد توثيق بريدك الإلكتروني، أرسل الطلب النهائي لمراجعته من الموارد البشرية.",
    "Your typed information is saved in this browser while you complete the form. For security, uploaded files must be selected again after a refresh.": "يتم حفظ المعلومات المكتوبة في هذا المتصفح أثناء إكمال النموذج. ولأسباب أمنية، يجب اختيار الملفات المرفوعة مرة أخرى بعد تحديث الصفحة.",
    "Privacy note": "ملاحظة الخصوصية",
    "Enter your email first": "أدخل بريدك الإلكتروني أولاً",
    "Enter your email address first.": "أدخل عنوان بريدك الإلكتروني أولاً.",
    "You have already applied to this job with this email.": "لقد قدمت بالفعل على هذه الوظيفة بهذا البريد الإلكتروني.",
    "This email already has an application for this job.": "يوجد طلب سابق لهذه الوظيفة بهذا البريد الإلكتروني.",
    "Email verified successfully. You can now submit the application.": "تم التحقق من البريد الإلكتروني بنجاح. يمكنك الآن إرسال الطلب.",
    "Email changed. Please verify the new email before submitting.": "تم تغيير البريد الإلكتروني. يرجى التحقق من البريد الجديد قبل الإرسال.",
    "This email can be used. Verify it before submitting.": "يمكن استخدام هذا البريد الإلكتروني. تحقق منه قبل الإرسال.",
    "Please check your email address.": "يرجى التحقق من عنوان بريدك الإلكتروني.",
    "Sending...": "جارٍ الإرسال...",
    "Verification code could not be sent.": "تعذر إرسال رمز التحقق.",
    "Verification code sent. Please check your email.": "تم إرسال رمز التحقق. يرجى فحص بريدك الإلكتروني.",
    "Verification code could not be sent. Please try again.": "تعذر إرسال رمز التحقق. يرجى المحاولة مرة أخرى.",
    "Enter the 6-digit code sent to your email.": "أدخل رمز التحقق المكوّن من 6 أرقام المرسل إلى بريدك الإلكتروني.",
    "Verifying...": "جارٍ التحقق...",
    "Email could not be verified.": "تعذر التحقق من البريد الإلكتروني.",
    "Verification failed. Please try again.": "فشل التحقق. يرجى المحاولة مرة أخرى.",
    "Additional documents": "مستندات إضافية",
    "CV / Resume": "السيرة الذاتية",
    "Supporting Document": "مستند داعم",
    "Certificate / License": "شهادة / رخصة",
    "Work authorization": "تصريح العمل",
    "Years of experience": "سنوات الخبرة",
    "Expected salary": "الراتب المتوقع",
    "Available from": "تاريخ التوفر",
    "Preferred interview time": "وقت المقابلة المفضل",
    "LinkedIn URL": "رابط لينكدإن",
    "Portfolio / website URL": "رابط الأعمال / الموقع",
    "Cover letter": "خطاب التعريف",
    "How did you hear about us?": "كيف عرفت عنا؟",
    "New inquiry": "استفسار جديد",
    "Share your requirement and our team will contact you.": "شارك متطلباتك وسيتواصل معك فريقنا.",
    "Project inquiry": "استفسار مشروع",
    "Contact methods": "وسائل التواصل",
    "Business hours": "ساعات العمل",
    "Questions": "الأسئلة",
    "Where to find us.": "أين تجدنا.",
    "Office Locations": "مواقع المكاتب",
    "Google map is not configured yet.": "لم يتم إعداد خريطة Google بعد.",
    "Add the Google Maps embed URL in Contact Page Settings.": "أضف رابط تضمين خرائط Google من إعدادات صفحة الاتصال.",
    "Admin note": "ملاحظة الإدارة",
    "The map and directions link are controlled from Contact Page Settings in admin.": "يتم التحكم في الخريطة ورابط الاتجاهات من إعدادات صفحة الاتصال في لوحة الإدارة.",
})

STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Profile review": "资料审核",
    "Upload documents": "上传文件",
    "Verify email separately": "单独验证邮箱",
    "Email verification": "邮箱验证",
    "Verify your email before submitting your application.": "提交申请前请先验证邮箱。",
    "Please verify this email before submitting the application.": "提交申请前请先验证此邮箱。",
    "Not verified": "未验证",
    "Verified": "已验证",
    "Verify Email": "验证邮箱",
    "Secure check": "安全验证",
    "Verify your email": "验证您的邮箱",
    "We will send a 6-digit code to your email. After successful verification, the submit button will unlock automatically.": "我们会向您的邮箱发送 6 位验证码。验证成功后，提交按钮将自动启用。",
    "Verification email": "验证邮箱",
    "Send Code": "发送验证码",
    "Cancel": "取消",
    "Submit application": "提交申请",
    "After your email is marked verified, submit the final application for HR review.": "邮箱验证完成后，请提交最终申请供 HR 审核。",
    "Your typed information is saved in this browser while you complete the form. For security, uploaded files must be selected again after a refresh.": "填写表单时，已输入的信息会保存在此浏览器中。出于安全考虑，刷新页面后需重新选择上传文件。",
    "Privacy note": "隐私说明",
    "Enter your email first": "请先输入邮箱",
    "Enter your email address first.": "请先输入电子邮箱地址。",
    "You have already applied to this job with this email.": "您已使用此邮箱申请过该职位。",
    "This email already has an application for this job.": "此邮箱已提交过该职位申请。",
    "Email verified successfully. You can now submit the application.": "邮箱验证成功。您现在可以提交申请。",
    "Email changed. Please verify the new email before submitting.": "邮箱已更改。提交前请验证新邮箱。",
    "This email can be used. Verify it before submitting.": "此邮箱可以使用。提交前请先验证。",
    "Please check your email address.": "请检查您的电子邮箱地址。",
    "Sending...": "正在发送...",
    "Verification code could not be sent.": "无法发送验证码。",
    "Verification code sent. Please check your email.": "验证码已发送。请检查邮箱。",
    "Verification code could not be sent. Please try again.": "无法发送验证码。请重试。",
    "Enter the 6-digit code sent to your email.": "请输入发送到您邮箱的 6 位验证码。",
    "Verifying...": "正在验证...",
    "Email could not be verified.": "邮箱无法验证。",
    "Verification failed. Please try again.": "验证失败。请重试。",
    "Additional documents": "其他文件",
    "CV / Resume": "简历",
    "Supporting Document": "支持文件",
    "Certificate / License": "证书 / 执照",
    "Work authorization": "工作许可",
    "Years of experience": "工作年限",
    "Expected salary": "期望薪资",
    "Available from": "可入职时间",
    "Preferred interview time": "偏好面试时间",
    "LinkedIn URL": "LinkedIn 链接",
    "Portfolio / website URL": "作品集 / 网站链接",
    "Cover letter": "求职说明",
    "How did you hear about us?": "您是如何了解我们的？",
    "New inquiry": "新的咨询",
    "Share your requirement and our team will contact you.": "请分享您的需求，我们的团队会与您联系。",
    "Project inquiry": "项目咨询",
    "Contact methods": "联系方式",
    "Business hours": "营业时间",
    "Questions": "问题",
    "Where to find us.": "我们的位置。",
    "Office Locations": "办公地点",
    "Google map is not configured yet.": "尚未配置 Google 地图。",
    "Add the Google Maps embed URL in Contact Page Settings.": "请在联系页面设置中添加 Google 地图嵌入链接。",
    "Admin note": "管理员说明",
    "The map and directions link are controlled from Contact Page Settings in admin.": "地图和路线链接由后台联系页面设置控制。",
})

# Upgrade 166 — FAQ answer fallbacks that frequently appear from seeded CMS pages.
VISIBLE_CMS_FALLBACK_TRANSLATIONS.setdefault("ar", {}).update({
    "SESCCO provides electrical engineering, civil and architectural fit-out works, contract support, electromechanical works and mechanical/fire-fighting services.": "تقدم SESCCO خدمات الهندسة الكهربائية والأعمال المدنية والتشطيبات المعمارية والدعم التعاقدي والأعمال الكهروميكانيكية والميكانيكية وأنظمة مكافحة الحريق.",
    "Yes. This page and its custom CMS sections can be edited from the Django admin panel.": "نعم. يمكن تعديل هذه الصفحة وأقسام CMS المخصصة الخاصة بها من لوحة إدارة Django.",
    "Yes. SESCCO supports projects across Saudi Arabia according to project requirements.": "نعم. تدعم SESCCO المشاريع في مختلف مناطق المملكة العربية السعودية حسب متطلبات المشروع.",
    "Our team aims to respond promptly after receiving your inquiry.": "يهدف فريقنا إلى الرد بسرعة بعد استلام استفسارك.",
    "Yes. Our contract support service provides qualified personnel and equipment support according to project needs.": "نعم. توفر خدمة الدعم التعاقدي لدينا كوادر مؤهلة ودعم معدات حسب احتياجات المشروع.",
})

VISIBLE_CMS_FALLBACK_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "SESCCO provides electrical engineering, civil and architectural fit-out works, contract support, electromechanical works and mechanical/fire-fighting services.": "SESCCO 提供电气工程、土建与建筑装修、合同支持、机电工程以及机械/消防系统服务。",
    "Yes. This page and its custom CMS sections can be edited from the Django admin panel.": "可以。此页面及其自定义 CMS 区块都可以在 Django 管理后台编辑。",
    "Yes. SESCCO supports projects across Saudi Arabia according to project requirements.": "可以。SESCCO 可根据项目需求在沙特阿拉伯各地提供项目支持。",
    "Our team aims to respond promptly after receiving your inquiry.": "我们的团队会在收到咨询后尽快回复。",
    "Yes. Our contract support service provides qualified personnel and equipment support according to project needs.": "可以。我们的合同支持服务可根据项目需求提供合格人员和设备支持。",
})




# Upgrade 168 — proper-name runtime rendering.
# Client/company/contractor names should be transliterated in Arabic where useful,
# and preserved as source names in Chinese. This avoids meaning-translation mistakes
# and also overrides older LocalizedContent rows that may contain mixed or partial names.
PROPER_NAME_TRANSLITERATIONS = {
    "ar": {
        "ARAMCO": "أرامكو",
        "Saudi Aramco": "أرامكو السعودية",
        "Saudi Electricity Company": "سعودي إلكتريسيتي كومباني",
        "Saudi Water Company": "سعودي ووتر كومباني",
        "Abahsain Consolidated Co.": "أبهسين كونسوليديتد كو.",
        "Abahsain Consolidating Co.": "أبهسين كونسوليديتنغ كو.",
        "Abhasain Consolidating Co.": "أبهسين كونسوليديتنغ كو.",
        "Energy & Power Contracting Co.": "إنرجي آند باور كونتراكتنغ كو.",
        "Energy & Power Cont. Co.": "إنرجي آند باور كونتراكتنغ كو.",
        "Energy & Power Cont. Co. Ltd.": "إنرجي آند باور كونتراكتنغ كو. ليمتد",
        "Rommel Electro Arabia": "روميل إلكترو أرابيا",
        "Future Technologies": "فيوتشر تكنولوجيز",
        "Al Rajhi Bank": "الراجحي بنك",
        "ABRAR": "أبرار",
        "EPC": "EPC",
        "DACO": "DACO",
        "BCC": "BCC",
        "MOBILY": "موبايلي",
        "Mobily": "موبايلي",
        "McDermott": "ماكديرموت",
        "McDermott Arabia": "ماكديرموت أرابيا",
        "L & T": "إل آند تي",
        "L&T": "إل آند تي",
        "Havelock One": "هافلوك ون",
        "Havelock1": "هافلوك ون",
        "Riyadh Airport Company": "رياض إيربورت كومباني",
        "Riyadh Airports Company": "رياض إيربورتس كومباني",
        "Novartis": "نوفارتس",
        "NHC": "NHC",
        "Royal Comision": "رويال كومشن",
        "Royal Commission": "رويال كومشن",
        "SABIC": "سابك",
        "SAIPEM": "سايبم",
        "Saudi Energy": "سعودي إنرجي",
        "SEPCO": "سيبكو",
        "SINOMA": "سينوما",
        "Roshan": "روشن",
        "The Avenues Khobar": "ذا أفنيوز الخبر",
        "Worley Parsons": "وورلي بارسونز",
        "SESCCO Team": "فريق SESCCO",
        "NG/SEC": "NG/SEC",
        "Industrial Client": "إندستريال كلاينت",
    },
    "zh-hans": {},
}

# Chinese should keep client/company/contractor source names unless an admin intentionally
# adds a reviewed localized name elsewhere. For public client cards and project party names,
# source-name preservation is safer than automatic meaning translation.
for _name in list(PROPER_NAME_TRANSLITERATIONS["ar"].keys()):
    PROPER_NAME_TRANSLITERATIONS["zh-hans"][_name] = _name



# Upgrade 169 — additional proper-name transliterations for client logo grids.
# These are organization names, so Arabic should show phonetic/proper-name
# transliteration and Chinese should preserve the source English name.
_PROPER_NAME_AR_UPGRADE_169 = {
    "EPC": "إي بي سي",
    "DACO": "داكو",
    "BCC": "بي سي سي",
    "NHC": "إن إتش سي",
    "SEC": "إس إي سي",
    "STC": "إس تي سي",
    "TR": "تي آر",
    "ABRAR": "أبرار",
    "Saudi National Bank": "سعودي ناشونال بنك",
    "Seven Entertainment Ventures": "سفن إنترتينمنت فينتشرز",
    "Saudi Electricity Company": "سعودي إلكتريسيتي كومباني",
    "Saudi Energy": "سعودي إنرجي",
    "SEPCO": "سيبكو",
    "SINOMA": "سينوما",
    "Royal Comision": "رويال كومشن",
    "Royal Commission": "رويال كومشن",
    "SAIPEM": "سايبم",
    "SABIC": "سابك",
    "Novartis": "نوفارتس",
    "Riyadh Airport Company": "رياض إيربورت كومباني",
    "Riyadh Airports Company": "رياض إيربورتس كومباني",
    "McDermott": "ماكديرموت",
    "MOBILY": "موبايلي",
    "Havelock1": "هافلوك ون",
    "Havelock One": "هافلوك ون",
    "L & T": "إل آند تي",
    "L&T": "إل آند تي",
    "ZAIN": "زين",
}

_PROPER_NAME_AR_UPGRADE_169.update({
    "Abahsain Consolidating Co": "أبهسين كونسوليديتنغ كو.",
    "Abahsain Consolidated Co": "أبهسين كونسوليديتد كو.",
    "Energy & Power Cont. Co. Ltd": "إنرجي آند باور كونتراكتنغ كو. ليمتد",
    "Energy & Power Cont. Co": "إنرجي آند باور كونتراكتنغ كو.",
    "Energy & Power Contracting Co": "إنرجي آند باور كونتراكتنغ كو.",
})
PROPER_NAME_TRANSLITERATIONS.setdefault("ar", {}).update(_PROPER_NAME_AR_UPGRADE_169)
PROPER_NAME_TRANSLITERATIONS.setdefault("zh-hans", {})
for _name in _PROPER_NAME_AR_UPGRADE_169:
    PROPER_NAME_TRANSLITERATIONS["zh-hans"][_name] = _name
STATIC_TRANSLATIONS.setdefault("ar", {}).update(_PROPER_NAME_AR_UPGRADE_169)


def _normalize_proper_name(value):
    text = str(value or "").strip()
    # RTL rendering can make trailing punctuation appear before the name; normalize common cases.
    return text.strip().strip(" ،。")


@register.simple_tag
def proper_name(value, field_name=None):
    """Render company/client/contractor names as proper names, not translated meanings."""
    if field_name and not isinstance(value, str):
        source = getattr(value, field_name, "")
    else:
        source = value
    raw = str(source or "").strip()
    normalized = _normalize_proper_name(raw)
    lang = get_language() or "en"
    if lang == "en":
        return raw
    lang_map = PROPER_NAME_TRANSLITERATIONS.get(lang, {})
    if normalized in lang_map:
        return lang_map[normalized]
    # Fall back to static translations only when an exact proper-name rule exists there.
    static_map = STATIC_TRANSLATIONS.get(lang, {})
    if normalized in static_map:
        return static_map[normalized]
    # Chinese: preserve source names by default. Arabic: if no rule exists, preserve the source
    # rather than attempting a meaning translation.
    return raw

# Upgrade 167 — final partial localization polish, company-name transliteration, and document/project labels.
# Proper names are transliterated where useful instead of translated by meaning.
STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Only one application is accepted per email for each job.": "يُقبل طلب واحد فقط لكل بريد إلكتروني لكل وظيفة.",
    "Attach certificates, licenses or portfolio files if they support the role.": "أرفق الشهادات أو الرخص أو ملفات الأعمال إذا كانت تدعم الوظيفة.",
    "Please verify your email before submitting the application.": "يرجى التحقق من بريدك الإلكتروني قبل إرسال الطلب.",
    "Please verify this email before submitting the application.": "يرجى التحقق من هذا البريد الإلكتروني قبل إرسال الطلب.",
    "PDF": "PDF",
    "DOC": "DOC",
    "Document": "مستند",
    "Portfolio": "معرض الأعمال",
    "Featured Project": "مشروع مميز",
    "Featured": "مميز",
    "Trusted Delivery": "تنفيذ موثوق",
    "Built for leading companies and organizations.": "تنفيذ موثوق لشركات وجهات رائدة.",
    "No clients added yet.": "لم تتم إضافة عملاء بعد.",
    "No projects found.": "لم يتم العثور على مشاريع.",
    "Try another keyword, status, year or category.": "جرّب كلمة بحث أو حالة أو سنة أو فئة أخرى.",
    "Search by project, client, contractor, location, scope...": "ابحث باسم المشروع أو العميل أو المقاول أو الموقع أو نطاق العمل...",
    "Search by project, client, contractor, location, scope…": "ابحث باسم المشروع أو العميل أو المقاول أو الموقع أو نطاق العمل...",
    "Showing 1 matching project.": "يتم عرض مشروع واحد مطابق.",
    "Showing {count} matching projects.": "يتم عرض {count} مشروعاً مطابقاً.",
    "Mechanical Projects": "المشاريع الميكانيكية",
    "Architectural & Fitout Projects": "مشاريع الأعمال المعمارية والتشطيبات",
    "Civil Projects": "المشاريع المدنية",
    "Electrical Projects": "المشاريع الكهربائية",
    "Telecommunication Projects": "مشاريع الاتصالات",
    "Fitout Projects": "مشاريع التشطيبات",
    "Core Clients": "عملاء رئيسيون",
    "Company Documents": "مستندات الشركة",
    "Document Center": "مركز المستندات",
    "Company Profile and Key Documents": "ملف الشركة والمستندات الرئيسية",
    "Access company profile documents, certifications and important supporting information.": "اطلع على ملف الشركة والشهادات والمعلومات الداعمة المهمة.",
    "Download or request SESCCO documents from the document center.": "حمّل مستندات SESCCO أو اطلبها من مركز المستندات.",
    "Document Center": "مركز المستندات",
    "Need a specific document?": "هل تحتاج إلى مستند محدد؟",
    "Request a Document": "طلب مستند",
    "Public": "عام",
    "Request Required": "يتطلب طلباً",
    "Private": "خاص",
    "SESCCO Company Profile": "ملف شركة SESCCO",
    "ISO Certification Pack": "حزمة شهادات ISO",
    "Vendor Registration Information": "معلومات تسجيل الموردين",
    "Official English company profile for Summit Engineering Solutions Cont. Co., including vendor codes, capabilities, services, project experience and certifications.": "ملف الشركة الرسمي باللغة الإنجليزية لشركة Summit Engineering Solutions Cont. Co. ويشمل رموز الموردين والقدرات والخدمات وخبرات المشاريع والشهادات.",
    "Quality, environmental and health & safety certification references.": "مراجع شهادات الجودة والبيئة والصحة والسلامة المهنية.",
    "Aramco Vendor Code 10114560 and SEC Vendor Code 02013075 reference information.": "معلومات مرجعية لرمز مورد أرامكو 10114560 ورمز مورد SEC 02013075.",
    "Vendor Registration": "تسجيل الموردين",
    "Key vendor credentials for project and procurement review.": "بيانات اعتماد الموردين الرئيسية لمراجعة المشاريع والمشتريات.",
    "SESCCO’s company profile lists Saudi Aramco Vendor Code 10114560 and Saudi Electricity Company Vendor Code 02013075.": "يذكر ملف شركة SESCCO رمز مورد أرامكو السعودية 10114560 ورمز مورد شركة الكهرباء السعودية 02013075.",
    "Safety": "السلامة",
    "Quality": "الجودة",
    "Reliability": "الموثوقية",
    "We build long-term partnerships through dependable execution.": "نبني شراكات طويلة الأمد من خلال تنفيذ موثوق.",
    "We prioritize safe work practices and protection of people and the environment.": "نعطي الأولوية لممارسات العمل الآمنة وحماية الأشخاص والبيئة.",
    "We focus on meeting project requirements and client expectations.": "نركز على تلبية متطلبات المشروع وتوقعات العميل.",
    "Months": "أشهر",
    "Month": "شهر",
    "Completed October 2024": "اكتمل في أكتوبر 2024",
    "Completed June 2023": "اكتمل في يونيو 2023",
    "Completed May 2025": "اكتمل في مايو 2025",
    "Completed August 2016": "اكتمل في أغسطس 2016",
    "Completed October 2016": "اكتمل في أكتوبر 2016",
    "SCK Certifications Pvt. Ltd.": "إس سي كيه سيرتيفيكيشنز برايفت ليمتد",
    "Saudi Electricity Company": "سعودي إلكتريسيتي كومباني",
    "Saudi Water Company": "سعودي ووتر كومباني",
    "Energy & Power Contracting Co.": "إنرجي آند باور كونتراكتنغ كو.",
    "Energy & Power Cont. Co.": "إنرجي آند باور كونتراكتنغ كو.",
    "Energy & Power Cont. Co. Ltd.": "إنرجي آند باور كونتراكتنغ كو. ليمتد",
    "Abahsain Consolidated Co.": "أبهسين كونسوليديتد كو.",
    "Abhasain Consolidating Co.": "أبهسين كونسوليديتنغ كو.",
    "Rommel Electro Arabia": "روميل إلكترو أرابيا",
    "Future Technologies": "فيوتشر تكنولوجيز",
    "SEPCO": "سيبكو",
    "SINOMA": "سينوما",
    "Havelock One": "هافلوك ون",
    "Havelock1": "هافلوك ون",
    "McDermott Arabia": "ماكديرموت أرابيا",
    "Worley Parsons": "وورلي بارسونز",
    "Roshan": "روشن",
    "The Avenues Khobar": "ذا أفنيوز الخبر",
    "ARAMCO": "أرامكو",
    "NG/SEC": "NG/SEC",
    "Industrial Client": "عميل صناعي",
    "SESCCO Team": "فريق SESCCO",
    "EPC": "EPC",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Only one application is accepted per email for each job.": "每个职位每个邮箱仅接受一份申请。",
    "Attach certificates, licenses or portfolio files if they support the role.": "如证书、执照或作品集有助于申请该职位，请一并上传。",
    "Please verify your email before submitting the application.": "提交申请前请先验证您的邮箱。",
    "Please verify this email before submitting the application.": "提交申请前请先验证此邮箱。",
    "PDF": "PDF",
    "DOC": "DOC",
    "Document": "文件",
    "Portfolio": "项目展示",
    "Featured Project": "精选项目",
    "Featured": "精选",
    "Trusted Delivery": "可靠交付",
    "Built for leading companies and organizations.": "服务于领先企业和机构。",
    "No clients added yet.": "暂无客户信息。",
    "No projects found.": "未找到项目。",
    "Try another keyword, status, year or category.": "请尝试其他关键词、状态、年份或类别。",
    "Search by project, client, contractor, location, scope...": "按项目、客户、承包商、地点或范围搜索...",
    "Search by project, client, contractor, location, scope…": "按项目、客户、承包商、地点或范围搜索...",
    "Showing 1 matching project.": "显示 1 个匹配项目。",
    "Showing {count} matching projects.": "显示 {count} 个匹配项目。",
    "Mechanical Projects": "机械项目",
    "Architectural & Fitout Projects": "建筑与装修项目",
    "Civil Projects": "土建项目",
    "Electrical Projects": "电气项目",
    "Telecommunication Projects": "通信项目",
    "Fitout Projects": "装修项目",
    "Core Clients": "核心客户",
    "Company Documents": "公司文件",
    "Company Profile and Key Documents": "公司简介与关键文件",
    "Access company profile documents, certifications and important supporting information.": "查看公司简介、认证和重要支持信息。",
    "Download or request SESCCO documents from the document center.": "在文件中心下载或申请 SESCCO 文件。",
    "Need a specific document?": "需要特定文件？",
    "Request a Document": "申请文件",
    "Public": "公开",
    "Request Required": "需申请",
    "Private": "私密",
    "SESCCO Company Profile": "SESCCO 公司简介",
    "ISO Certification Pack": "ISO 认证包",
    "Vendor Registration Information": "供应商注册信息",
    "Official English company profile for Summit Engineering Solutions Cont. Co., including vendor codes, capabilities, services, project experience and certifications.": "Summit Engineering Solutions Cont. Co. 官方英文公司简介，包含供应商代码、能力、服务、项目经验和认证。",
    "Quality, environmental and health & safety certification references.": "质量、环境和职业健康安全认证资料。",
    "Aramco Vendor Code 10114560 and SEC Vendor Code 02013075 reference information.": "Aramco 供应商代码 10114560 与 SEC 供应商代码 02013075 参考信息。",
    "Vendor Registration": "供应商注册",
    "Key vendor credentials for project and procurement review.": "用于项目和采购审核的关键供应商资质。",
    "SESCCO’s company profile lists Saudi Aramco Vendor Code 10114560 and Saudi Electricity Company Vendor Code 02013075.": "SESCCO 公司简介列明 Saudi Aramco 供应商代码 10114560 和 Saudi Electricity Company 供应商代码 02013075。",
    "Safety": "安全",
    "Quality": "质量",
    "Reliability": "可靠性",
    "We build long-term partnerships through dependable execution.": "我们通过可靠执行建立长期合作关系。",
    "We prioritize safe work practices and protection of people and the environment.": "我们优先考虑安全作业以及人员和环境保护。",
    "We focus on meeting project requirements and client expectations.": "我们专注于满足项目要求和客户期望。",
    "Months": "个月",
    "Month": "个月",
    "Completed October 2024": "2024 年 10 月完成",
    "Completed June 2023": "2023 年 6 月完成",
    "Completed May 2025": "2025 年 5 月完成",
    "Completed August 2016": "2016 年 8 月完成",
    "Completed October 2016": "2016 年 10 月完成",
    "Saudi Electricity Company": "Saudi Electricity Company",
    "Saudi Water Company": "Saudi Water Company",
    "Energy & Power Contracting Co.": "Energy & Power Contracting Co.",
    "Energy & Power Cont. Co.": "Energy & Power Cont. Co.",
    "Energy & Power Cont. Co. Ltd.": "Energy & Power Cont. Co. Ltd.",
    "Abahsain Consolidated Co.": "Abahsain Consolidated Co.",
    "Abhasain Consolidating Co.": "Abhasain Consolidating Co.",
    "Rommel Electro Arabia": "Rommel Electro Arabia",
    "Future Technologies": "Future Technologies",
    "SEPCO": "SEPCO",
    "SINOMA": "SINOMA",
    "Havelock One": "Havelock One",
    "Havelock1": "Havelock One",
    "McDermott Arabia": "McDermott Arabia",
    "Worley Parsons": "Worley Parsons",
    "Roshan": "Roshan",
    "The Avenues Khobar": "The Avenues Khobar",
    "ARAMCO": "ARAMCO",
    "NG/SEC": "NG/SEC",
    "Industrial Client": "Industrial Client",
    "SESCCO Team": "SESCCO Team",
    "EPC": "EPC",
})

# The same mappings are intentionally added as CMS fallbacks so seeded/admin records
# that store English source values still render clean localized output.
for _lang in ("ar", "zh-hans"):
    VISIBLE_CMS_FALLBACK_TRANSLATIONS.setdefault(_lang, {}).update(STATIC_TRANSLATIONS.get(_lang, {}))


STATIC_TRANSLATIONS.setdefault("ar", {}).update({
    "Abahsain Consolidating Co.": "أبهسين كونسوليديتنغ كو.",
    "Al Rajhi Bank": "الراجحي بنك",
    "ABRAR": "أبرار",
    "DACO": "DACO",
    "BCC": "BCC",
    "MOBILY": "موبايلي",
    "Mobily": "موبايلي",
    "McDermott": "ماكديرموت",
    "L & T": "إل آند تي",
    "L&T": "إل آند تي",
    "Riyadh Airport Company": "رياض إيربورت كومباني",
    "Riyadh Airports Company": "رياض إيربورتس كومباني",
    "Novartis": "نوفارتس",
    "NHC": "NHC",
    "Royal Comision": "رويال كومشن",
    "Royal Commission": "رويال كومشن",
    "SABIC": "سابك",
    "SAIPEM": "سايبم",
    "Saudi Energy": "سعودي إنرجي",
})
STATIC_TRANSLATIONS.setdefault("zh-hans", {}).update({
    "Abahsain Consolidating Co.": "Abahsain Consolidating Co.",
    "Al Rajhi Bank": "Al Rajhi Bank",
    "ABRAR": "ABRAR",
    "DACO": "DACO",
    "BCC": "BCC",
    "MOBILY": "MOBILY",
    "Mobily": "Mobily",
    "McDermott": "McDermott",
    "L & T": "L & T",
    "L&T": "L&T",
    "Riyadh Airport Company": "Riyadh Airport Company",
    "Riyadh Airports Company": "Riyadh Airports Company",
    "Novartis": "Novartis",
    "NHC": "NHC",
    "Royal Comision": "Royal Comision",
    "Royal Commission": "Royal Commission",
    "SABIC": "SABIC",
    "SAIPEM": "SAIPEM",
    "Saudi Energy": "Saudi Energy",
})
for _lang in ("ar", "zh-hans"):
    VISIBLE_CMS_FALLBACK_TRANSLATIONS.setdefault(_lang, {}).update(STATIC_TRANSLATIONS.get(_lang, {}))
