# Generated by Django 5.2.15 on 2026-06-11 20:42

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('day_label', models.CharField(max_length=80)),
                ('hours', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='Summit Engineering Solutions Contracting Co.', max_length=255)),
                ('short_name', models.CharField(default='SESCCO', max_length=80)),
                ('tagline', models.CharField(default='Where high-quality engineering meets reliable service.', max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('established_year', models.PositiveIntegerField(default=2015)),
                ('aramco_vendor_code', models.CharField(blank=True, default='10114560', max_length=80)),
                ('sec_vendor_code', models.CharField(blank=True, default='02013075', max_length=80)),
                ('phone_primary', models.CharField(blank=True, default='+966 50 969 6018', max_length=50)),
                ('phone_secondary', models.CharField(blank=True, default='+966 54 004 8692', max_length=50)),
                ('email_primary', models.EmailField(blank=True, default='info@sescco.com', max_length=254)),
                ('email_secondary', models.EmailField(blank=True, default='imran@sescco.com', max_length=254)),
                ('email_third', models.EmailField(blank=True, default='mehrab@sescco.com', max_length=254)),
                ('address', models.CharField(blank=True, default='Dammam, Saudi Arabia', max_length=255)),
                ('city', models.CharField(blank=True, default='Dammam', max_length=120)),
                ('country', models.CharField(blank=True, default='Saudi Arabia', max_length=120)),
                ('website_url', models.URLField(blank=True, default='https://sescco.com')),
                ('map_embed_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=255)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('show_on_contact_page', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.SlugField(help_text='Example: global-main, homepage, services, contact', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=120)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='cta/')),
                ('style', models.CharField(default='blue', max_length=80)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CTASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header_cta_text', models.CharField(default='Get in Touch', max_length=80)),
                ('header_cta_url', models.CharField(default='/contact/', max_length=255)),
                ('main_cta_title', models.CharField(default='Let’s Build Something Great Together.', max_length=255)),
                ('main_cta_subtitle', models.CharField(default='Ready to start your next project? Our team is here to help.', max_length=255)),
                ('main_cta_button_text', models.CharField(default='Get in Touch Today', max_length=80)),
                ('main_cta_button_url', models.CharField(default='/contact/', max_length=255)),
            ],
            options={
                'verbose_name': 'CTA Settings',
                'verbose_name_plural': 'CTA Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=255)),
                ('open_in_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default='Head Office', max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('map_url', models.URLField(blank=True)),
                ('map_embed_url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('asset_type', models.CharField(choices=[('hero', 'Hero Background'), ('about', 'About Image'), ('pattern', 'Pattern / Decoration'), ('footer', 'Footer Graphic'), ('placeholder', 'Placeholder')], default='placeholder', max_length=40)),
                ('image', models.ImageField(upload_to='site-assets/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='SESCCO', max_length=255)),
                ('domain', models.CharField(default='sescco.com', max_length=255)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('enable_multilingual', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('default_seo_title', models.CharField(blank=True, max_length=255)),
                ('default_seo_description', models.TextField(blank=True)),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('icon_text', models.CharField(blank=True, help_text='Example: in, f, X', max_length=20)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_color', models.CharField(default='#0758d8', max_length=20)),
                ('secondary_color', models.CharField(default='#042a5f', max_length=20)),
                ('accent_color', models.CharField(default='#00a6df', max_length=20)),
                ('dark_color', models.CharField(default='#061a34', max_length=20)),
                ('light_color', models.CharField(default='#f4f8fd', max_length=20)),
                ('header_style', models.CharField(default='standard', max_length=50)),
                ('footer_style', models.CharField(default='standard', max_length=50)),
                ('button_style', models.CharField(default='rounded', max_length=50)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
        migrations.CreateModel(
            name='TrustMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('show_on_home', models.BooleanField(default=True)),
                ('show_on_about', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=255)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footercolumn')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalizedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('companyprofile', 'Company Profile'), ('navigationmenu', 'Navigation'), ('footercolumn', 'Footer Column'), ('footerlink', 'Footer Link'), ('ctasettings', 'CTA Settings'), ('ctasection', 'CTA Section'), ('homehero', 'Home Hero'), ('homeaboutblock', 'Home About'), ('homesectionsettings', 'Home Settings'), ('homehighlight', 'Home Highlight'), ('whychooseitem', 'Why Choose Item'), ('page', 'Page'), ('pagesection', 'Page Section'), ('missionvisionitem', 'Mission/Vision'), ('valueitem', 'Value Item'), ('timelineitem', 'Timeline Item'), ('leadershipmessage', 'Leadership Message'), ('statitem', 'Stats'), ('faq', 'FAQ'), ('servicelistpagesettings', 'Service Page Settings'), ('service', 'Service'), ('servicekeypoint', 'Service Key Point'), ('servicedeliverable', 'Service Deliverable'), ('servicefeature', 'Service Feature'), ('serviceprocessstep', 'Service Process'), ('servicefaq', 'Service FAQ'), ('servicecta', 'Service CTA'), ('projectlistpagesettings', 'Project Page Settings'), ('project', 'Project'), ('projectliststat', 'Project Stat'), ('projectmetric', 'Project Metric'), ('projectscopeitem', 'Project Scope Item'), ('projectcta', 'Project CTA'), ('trustpagesettings', 'Trust Page Settings'), ('client', 'Client'), ('partner', 'Partner'), ('certificate', 'Certificate'), ('accreditation', 'Accreditation'), ('standard', 'Standard'), ('complianceblock', 'Compliance Block'), ('trustmetric', 'Trust Metric'), ('testimonial', 'Testimonial'), ('downloadspagesettings', 'Downloads Page Settings'), ('downloaddocument', 'Document'), ('documentpagecta', 'Document CTA'), ('contactpagesettings', 'Contact Page Settings'), ('inquirysubject', 'Inquiry Subject'), ('contactmethod', 'Contact Method'), ('officelocation', 'Office Location'), ('businesshour', 'Business Hour')], help_text='Select which type of content this translation belongs to.', max_length=120)),
                ('object_id', models.PositiveIntegerField()),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('zh-hans', 'Chinese')], max_length=20)),
                ('field_name', models.CharField(help_text='Example: title, body, short_description', max_length=120)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
            ],
            options={
                'verbose_name': 'Localized Content Override',
                'verbose_name_plural': 'Localized Content Overrides',
                'ordering': ['content_type', 'object_id', 'language_code', 'field_name'],
                'unique_together': {('content_type', 'object_id', 'language_code', 'field_name')},
            },
        ),
    ]
