# Generated by upgrade 86: footer social heading and developer credit settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_trustmetric_icon_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_social_title",
            field=models.CharField(default="Find us on social media", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_developer_credit",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="developer_credit_label",
            field=models.CharField(default="Website developed by", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="developer_name",
            field=models.CharField(default="A2TDEV", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="developer_url",
            field=models.URLField(blank=True, default="https://a2tdev.com"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="developer_seo_description",
            field=models.CharField(blank=True, default="Professional website design and development partner for SESCCO.", max_length=255),
        ),
    ]
