# Generated by Django 5.2.15 on 2026-06-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_localizedcontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizedcontent',
            name='content_type',
            field=models.CharField(choices=[('statictext', 'Static UI Text'), ('companyprofile', 'Company Profile'), ('navigationmenu', 'Navigation'), ('footercolumn', 'Footer Column'), ('footerlink', 'Footer Link'), ('ctasettings', 'CTA Settings'), ('ctasection', 'CTA Section'), ('homehero', 'Home Hero'), ('homeaboutblock', 'Home About'), ('homesectionsettings', 'Home Settings'), ('homehighlight', 'Home Highlight'), ('whychooseitem', 'Why Choose Item'), ('page', 'Page'), ('pagesection', 'Page Section'), ('missionvisionitem', 'Mission/Vision'), ('valueitem', 'Value Item'), ('timelineitem', 'Timeline Item'), ('leadershipmessage', 'Leadership Message'), ('statitem', 'Stats'), ('faq', 'FAQ'), ('servicelistpagesettings', 'Service Page Settings'), ('service', 'Service'), ('servicekeypoint', 'Service Key Point'), ('servicedeliverable', 'Service Deliverable'), ('servicefeature', 'Service Feature'), ('serviceprocessstep', 'Service Process'), ('servicefaq', 'Service FAQ'), ('servicecta', 'Service CTA'), ('projectlistpagesettings', 'Project Page Settings'), ('project', 'Project'), ('projectliststat', 'Project Stat'), ('projectmetric', 'Project Metric'), ('projectscopeitem', 'Project Scope Item'), ('projectcta', 'Project CTA'), ('trustpagesettings', 'Trust Page Settings'), ('client', 'Client'), ('partner', 'Partner'), ('certificate', 'Certificate'), ('accreditation', 'Accreditation'), ('standard', 'Standard'), ('complianceblock', 'Compliance Block'), ('trustmetric', 'Trust Metric'), ('testimonial', 'Testimonial'), ('downloaddocument', 'Document'), ('documentpagecta', 'Document CTA'), ('careerpagesettings', 'Career Page Settings'), ('careerstat', 'Career Stat'), ('careerbenefit', 'Career Benefit'), ('careerprocessstep', 'Career Process Step'), ('careerdepartment', 'Career Department'), ('jobopening', 'Job Opening'), ('contactpagesettings', 'Contact Page Settings'), ('inquirysubject', 'Inquiry Subject'), ('contactmethod', 'Contact Method'), ('officelocation', 'Office Location'), ('businesshour', 'Business Hour')], help_text='Select which type of content this translation belongs to.', max_length=120),
        ),
    ]
