# Generated by Django 5.2.15 on 2026-06-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_footer_social_developer_credit'),
        ('core', '0005_alter_localizedcontent_content_type'),
    ]

    operations = [
    ]
