# Generated by Django 5.2.15 on 2026-06-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_upgrade167_localization_polish'),
        ('core', '0006_merge_20260624_1853'),
    ]

    operations = [
    ]
