# Generated by Django 5.2.15 on 2026-06-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_upgrade168_proper_names'),
        ('core', '0007_merge_20260626_2059'),
    ]

    operations = [
    ]
