# Generated by Django 5.2.15 on 2026-06-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_upgrade169_client_names_hero_center'),
        ('core', '0008_merge_20260626_2140'),
    ]

    operations = [
    ]
