# Generated by Django 5.2.15 on 2026-06-11 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('icon_text', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Document categories',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentPageCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Can’t find what you’re looking for?', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Contact our team and we’ll help you with the document you need.')),
                ('button_text', models.CharField(default='Request a Document', max_length=120)),
                ('button_url', models.CharField(default='/downloads/request/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Page CTA',
                'verbose_name_plural': 'Document Page CTA',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('requested_document', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadsPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Downloads', max_length=120)),
                ('hero_title', models.CharField(default='Company Profile & Key Documents', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='Access company profiles, certifications, policies and other important documents.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='downloads/page/')),
                ('intro_title', models.CharField(default='Document Center', max_length=255)),
                ('intro_text', models.TextField(blank=True)),
                ('show_category_tabs', models.BooleanField(default=True)),
                ('show_search', models.BooleanField(default=True)),
                ('show_featured_document', models.BooleanField(default=True)),
                ('show_document_table', models.BooleanField(default=True)),
                ('show_request_document', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Downloads Page Settings',
                'verbose_name_plural': 'Downloads Page Settings',
            },
        ),
        migrations.CreateModel(
            name='DownloadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/files/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='documents/thumbnails/')),
                ('file_type', models.CharField(blank=True, default='PDF', max_length=40)),
                ('file_size', models.CharField(blank=True, max_length=40)),
                ('version', models.CharField(blank=True, default='2024.1', max_length=40)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('requires_request', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('request', 'Request Required'), ('private', 'Private')], default='public', max_length=30)),
                ('preview_enabled', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documents.downloaddocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
