# Generated by Django 5.2.15 on 2026-06-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='Example: /old-page/', max_length=255, unique=True)),
                ('new_path', models.CharField(help_text='Example: /new-page/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('permanent', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RobotsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='User-agent: *\nAllow: /\nSitemap: /sitemap.xml')),
            ],
            options={
                'verbose_name': 'Robots.txt Settings',
                'verbose_name_plural': 'Robots.txt Settings',
            },
        ),
        migrations.CreateModel(
            name='SchemaMarkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('page_path', models.CharField(blank=True, help_text='Example: /about/. Leave blank for global.', max_length=255)),
                ('json_ld', models.TextField(help_text='Paste valid JSON-LD.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
