"""Build the public-site CSS bundle in the same order as the legacy links.

Run this after editing any source stylesheet. The bundle is committed so a
production request never needs a runtime asset build step.
"""

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CSS_DIR = ROOT / "static" / "css"
OUTPUT = CSS_DIR / "site.bundle.css"

SOURCES = (
    "style.css",
    "prototype_alignment.css",
    "rtl.css",
    "career_ux.css",
    "rtl_layout_stabilization.css",
    "rtl_hero_restore_141.css",
    "rtl_hero_spacing_breadcrumbs_142.css",
    "visible_localization_polish_143.css",
    "sticky_local_nav_top_144.css",
    "sticky_local_nav_header_sync_145.css",
    "certificate_premium_cards_147.css",
    "hero_center_proper_names_169.css",
    "home_hero_background_visibility_170.css",
    "home_hero_consistent_dark_171.css",
    "home_sphere_no_extra_text_172.css",
    "project_cards_fixed_media_176.css",
    "nav_compact_sphere_smooth_177.css",
    "accordion_consistency_184.css",
    "gsap_prehide_186.css",
    "mobile_polish_188.css",
    "hero_card_spacing_clarity_194.css",
    "home_mobile_photo_visible_198.css",
    "mobile_site_polish_203.css",
    "client_logo_rail_218.css",
    "vendor_company_logos_219.css",
    "project_category_tabs_220.css",
    "project_client_logos_221.css",
)


def build() -> None:
    sections = [
        "/* Generated by scripts/build_css_bundle.py. Do not edit directly. */\n"
    ]
    for filename in SOURCES:
        source = CSS_DIR / filename
        sections.append(f"\n/* source: {filename} */\n")
        sections.append(source.read_text(encoding="utf-8").rstrip())
        sections.append("\n")
    OUTPUT.write_text("".join(sections), encoding="utf-8", newline="\n")
    print(f"Built {OUTPUT.relative_to(ROOT)} from {len(SOURCES)} stylesheets")


if __name__ == "__main__":
    build()
