# Generated by ChatGPT upgrade 41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_whychooseitem_icon_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadershipmessage",
            name="background_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional full-width parallax background image for homepage leadership message section. Recommended 1920x900px or larger.",
                null=True,
                upload_to="leadership/backgrounds/",
            ),
        ),
    ]
