# Generated by Django 5.2.15 on 2026-06-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_homehero_show_sphere'),
        ('pages', '0009_homeherosphereconfig'),
    ]

    operations = [
    ]
