# Generated by Django 5.2.15 on 2026-06-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_merge_20260625_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeHeroSphereConfig',
        ),
    ]
