# Generated by Django 5.2.15 on 2026-06-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_home_certificates_limit_default_six'),
        ('pages', '0011_delete_homeherosphereconfig'),
    ]

    operations = [
    ]
