# Generated by Django 5.2.15 on 2026-06-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_certifications_clients_section_order'),
        ('pages', '0012_merge_20260626_1923'),
    ]

    operations = [
    ]
