# Generated by Django 5.2.15 on 2026-06-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_home_sphere_visual_cards_only'),
        ('pages', '0013_merge_20260626_1950'),
    ]

    operations = [
    ]
