# Generated by Django 5.2.15 on 2026-06-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_certifications_clients_page_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcategory',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Project contractor', 'verbose_name_plural': 'Project contractors'},
        ),
    ]
