# Generated by Django 5.2.15 on 2026-06-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon_text', models.CharField(blank=True, default='✓', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Career Benefit',
                'verbose_name_plural': 'Career Benefits',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('step_number', models.CharField(blank=True, default='', max_length=12)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('icon_text', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Career Process Step',
                'verbose_name_plural': 'Career Process Steps',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('icon_text', models.CharField(blank=True, default='', max_length=20)),
                ('show_on_hero', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Career Stat',
                'verbose_name_plural': 'Career Stats',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='application_guide_text',
            field=models.TextField(blank=True, default='Use PDF or DOCX files where possible. Shortlisted applicants will receive interview details by email.'),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='application_guide_title',
            field=models.CharField(default='Application checklist', max_length=180),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='benefits_eyebrow',
            field=models.CharField(default='Why Work With Us', max_length=120),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='benefits_text',
            field=models.TextField(blank=True, default='SESCCO career opportunities are built around project readiness, safe execution, technical growth and reliable teamwork.'),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='benefits_title',
            field=models.CharField(default='A practical environment for serious professionals', max_length=255),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='empty_jobs_text',
            field=models.TextField(blank=True, default='Try another search or check again later for new opportunities.'),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='empty_jobs_title',
            field=models.CharField(default='No open jobs found', max_length=180),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='form_help_text',
            field=models.TextField(blank=True, default='Prepare a clear CV and attach documents that support the role. Make sure your email and phone number are correct.'),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='form_help_title',
            field=models.CharField(default='Before submitting', max_length=180),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='hero_primary_button_text',
            field=models.CharField(default='View Open Jobs', max_length=120),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='hero_primary_button_url',
            field=models.CharField(default='#open-roles', max_length=255),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='hero_secondary_button_text',
            field=models.CharField(default='Contact HR', max_length=120),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='hero_secondary_button_url',
            field=models.CharField(default='/contact/', max_length=255),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='meta_description',
            field=models.CharField(blank=True, default='Explore career opportunities at SESCCO and apply online with your CV and supporting documents.', max_length=320),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='meta_title',
            field=models.CharField(blank=True, default='Careers | SESCCO', max_length=255),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='process_eyebrow',
            field=models.CharField(default='Hiring Process', max_length=120),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='recruitment_email',
            field=models.EmailField(blank=True, default='hr@sescco.com', max_length=254),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='show_benefits',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='show_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='success_eyebrow',
            field=models.CharField(default='Application Submitted', max_length=120),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='success_text',
            field=models.TextField(blank=True, default='Your application has been received. Our HR team will review your CV and documents. Shortlisted applicants will receive an interview invitation by email.'),
        ),
        migrations.AddField(
            model_name='careerpagesettings',
            name='success_title',
            field=models.CharField(default='Thank you for applying.', max_length=220),
        ),
    ]
