# Generated by Django 5.2.15 on 2026-06-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_email_verification_and_application_flags'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='careeremailverification',
            new_name='careers_car_job_id_5da641_idx',
            old_name='careers_emai_job_id_56c57d_idx',
        ),
        migrations.RenameIndex(
            model_name='careeremailverification',
            new_name='careers_car_verifie_0bdc23_idx',
            old_name='careers_emai_verifie_f04b16_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='careers_job_job_id_1bb12b_idx',
            old_name='careers_app_job_80b560_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='careers_job_status_c56afb_idx',
            old_name='careers_app_status_8fb3d8_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplicationemaillog',
            new_name='careers_job_email_t_437ec6_idx',
            old_name='careers_app_email_t_44b4bb_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplicationemaillog',
            new_name='careers_job_success_d9bc99_idx',
            old_name='careers_app_success_7b43b9_idx',
        ),
        migrations.RenameIndex(
            model_name='jobopening',
            new_name='careers_job_status_df396f_idx',
            old_name='careers_job_status_f56d0a_idx',
        ),
        migrations.RenameIndex(
            model_name='jobopening',
            new_name='careers_job_is_feat_95f923_idx',
            old_name='careers_job_feature_2d8a52_idx',
        ),
        migrations.AlterField(
            model_name='careerpagesettings',
            name='application_guide_text',
            field=models.TextField(blank=True, default='Use PDF, DOC or DOCX files only. Shortlisted applicants will receive interview details by email.'),
        ),
        migrations.AlterField(
            model_name='careerpagesettings',
            name='document_upload_text',
            field=models.TextField(blank=True, default='Upload your CV and any supporting certificates, licenses or project documents as PDF, DOC or DOCX files. Multiple additional documents are supported.'),
        ),
    ]
